INSERT INTO weapon_family VALUES (1, 'None' );


INSERT INTO weapon VALUES ( 1, 'Club', '', 0.1, 2, 1, 2, 0, 20, 2, 0, 0, 0, 0, 0, 1, 0 );
INSERT INTO weapon VALUES ( 2, 'Dagger', '', 2, 1, 1, 2, 0, 20, 2, 0, 0, 0, 0, 3, 1, 20 );
INSERT INTO weapon VALUES ( 3, 'Great-Club', '', 0.2, 10, 1, 4, 0, 20, 2, 0, 0, 0, 2, 0, 1, 0 );
INSERT INTO weapon VALUES ( 4, 'Hand-Axe', '', 5, 2, 1, 3, 0, 20, 2, 0, 0, 0, 0, 3, 1, 20 );
INSERT INTO weapon VALUES ( 5, 'Javelin', '', 0.5, 2, 1, 3, 0, 20, 2, 0, 0, 0, 1, 3, 1, 30 );
INSERT INTO weapon VALUES ( 6, 'Light Hammer', '', 2, 2, 1, 2, 0, 20, 2, 0, 0, 0, 0, 3, 1, 0 );
INSERT INTO weapon VALUES ( 7, 'Mace', '', 5, 4, 1, 3, 0, 20, 2, 0, 0, 0, 1, 0, 1, 0 );
INSERT INTO weapon VALUES ( 8, 'Quarterstaff', '', 0.2, 4, 1, 3, 0, 20, 2, 0, 0, 0, 1, 0, 1, 0 );
INSERT INTO weapon VALUES ( 9, 'Quarterstaff (Versatile)', '', 0.2, 4, 1, 4, 0, 20, 2, 0, 0, 0, 1, 0, 1, 0 );
INSERT INTO weapon VALUES ( 10, 'Sickle', '', 1, 2, 1, 2, 0, 20, 2, 0, 0, 0, 0, 0, 1, 0 );
INSERT INTO weapon VALUES ( 11, 'Spear', '', 1, 3, 1, 3, 0, 20, 2, 0, 0, 0, 1, 3, 1, 20 );
INSERT INTO weapon VALUES ( 12, 'Spear  (Versatile)', '', 1, 3, 1, 4, 0, 20, 2, 0, 0, 0, 1, 3, 1, 20 );
INSERT INTO weapon VALUES ( 13, 'Crossbow, Light', '', 25, 5, 1, 4, 0, 20, 2, 0, 0, 1, 2, 4, 1, 80 );
INSERT INTO weapon VALUES ( 14, 'Dart', '', 0.05, 0.25, 1, 2, 0, 20, 2, 0, 0, 1, 1, 3, 1, 20 );
INSERT INTO weapon VALUES ( 15, 'Shortbow', '', 25, 2, 1, 3, 0, 20, 2, 0, 0, 1, 2, 4, 1, 80 );
INSERT INTO weapon VALUES ( 16, 'Sling', '', 0.1, 0, 1, 2, 0, 20, 2, 0, 0, 1, 1, 4, 1, 30 );
INSERT INTO weapon VALUES ( 17, 'Battleaxe', '', 10, 4, 1, 4, 0, 20, 2, 1, 0, 0, 1, 0, 1, 0 );
INSERT INTO weapon VALUES ( 18, 'Battleaxe (Versatile)', '', 10, 4, 1, 5, 0, 20, 2, 1, 0, 0, 1, 0, 1, 0 );
INSERT INTO weapon VALUES ( 19, 'Flail', '', 10, 2, 1, 4, 0, 20, 2, 1, 0, 0, 1, 0, 1, 0 );
INSERT INTO weapon VALUES ( 20, 'Glaive', '', 20, 6, 1, 5, 0, 20, 2, 1, 0, 0, 2, 1, 1, 0 );
INSERT INTO weapon VALUES ( 21, 'Greataxe', '', 30, 7, 1, 6, 0, 20, 2, 1, 0, 0, 2, 0, 1, 0 );
INSERT INTO weapon VALUES ( 22, 'Great-sword', '', 50, 6, 2, 3, 0, 20, 2, 1, 0, 0, 2, 0, 1, 0 );
INSERT INTO weapon VALUES ( 23, 'Halberd', '', 20, 6, 1, 5, 0, 20, 2, 1, 0, 0, 2, 1, 1, 0 );
INSERT INTO weapon VALUES ( 24, 'Lance', 'You have disadvantage when you use a lance to attack a target within 5 feet of you. Also, a lance requires two hands to wield when you aren''t mounted.', 10, 6, 1, 6, 0, 20, 2, 1, 0, 0, 1, 1, 1, 0 );
INSERT INTO weapon VALUES ( 25, 'Longsword', '', 15, 3, 1, 4, 0, 20, 2, 1, 0, 0, 1, 0, 1, 0 );
INSERT INTO weapon VALUES ( 26, 'Longsword (Versatile)', '', 15, 3, 1, 5, 0, 20, 2, 1, 0, 0, 1, 0, 1, 0 );
INSERT INTO weapon VALUES ( 27, 'Maul', '', 10, 10, 2, 3, 0, 20, 2, 1, 0, 0, 2, 0, 1, 0 );
INSERT INTO weapon VALUES ( 28, 'Morningstar', '', 15, 4, 1, 4, 0, 20, 2, 1, 0, 0, 1, 0, 1, 0 );
INSERT INTO weapon VALUES ( 29, 'Pike', '', 5, 18, 1, 5, 0, 20, 2, 1, 0, 0, 2, 1, 1, 0 );
INSERT INTO weapon VALUES ( 30, 'Rapier', '', 25, 2, 1, 4, 0, 20, 2, 1, 0, 0, 1, 0, 1, 0 );
INSERT INTO weapon VALUES ( 31, 'Scimitar', '', 25, 3, 1, 3, 0, 20, 2, 1, 0, 0, 0, 0, 1, 0 );
INSERT INTO weapon VALUES ( 32, 'Short-sword', '', 10, 2, 1, 3, 0, 20, 2, 1, 0, 0, 0, 0, 1, 0 );
INSERT INTO weapon VALUES ( 33, 'Trident', '', 5, 4, 1, 3, 0, 20, 2, 1, 0, 0, 1, 3, 1, 20 );
INSERT INTO weapon VALUES ( 34, 'Trident', '', 5, 4, 1, 4, 0, 20, 2, 1, 0, 0, 1, 3, 1, 20 );
INSERT INTO weapon VALUES ( 35, 'War pick', '', 5, 2, 1, 4, 0, 20, 2, 1, 0, 0, 1, 0, 1, 0 );
INSERT INTO weapon VALUES ( 36, 'Warhammer', '', 15, 2, 1, 4, 0, 20, 2, 1, 0, 0, 1, 0, 1, 0 );
INSERT INTO weapon VALUES ( 37, 'Warhammer (Versatile)', '', 15, 2, 1, 5, 0, 20, 2, 1, 0, 0, 1, 0, 1, 0 );
INSERT INTO weapon VALUES ( 38, 'Whip', '', 2, 3, 1, 2, 0, 20, 2, 1, 0, 0, 1, 0, 1, 0 );
INSERT INTO weapon VALUES ( 39, 'Blowgun', '', 10, 1, 1, 0, 0, 20, 2, 1, 0, 1, 1, 4, 1, 25 );
INSERT INTO weapon VALUES ( 40, 'Crossbow, Hand', '', 75, 3, 1, 3, 0, 20, 2, 1, 0, 1, 0, 4, 1, 30 );
INSERT INTO weapon VALUES ( 41, 'Crossbow, Heavy', '', 50, 18, 1, 5, 0, 20, 2, 1, 0, 1, 2, 4, 1, 100 );
INSERT INTO weapon VALUES ( 42, 'Longbow', '', 50, 2, 1, 4, 0, 20, 2, 1, 0, 1, 2, 4, 1, 150 );
INSERT INTO weapon VALUES ( 43, 'Net', 'A Large or smaller creature hit by a net is restrained until it is freed. A net has no effect on creatures that are formless, or creatures that are Huge or larger. A creature can use its action to make a DC 10 Strength check, freeing itself or another creature within its reach on a success. Dealing 5 slashing damage to the net (AC 10) also frees the creature without harming it, ending the effect and destroying the net. When you use an action, bonus action, or reaction to attack with a net, you can make only one attack regardless of the number of attacks you can normally make.', 1, 3, 0, 0, 0, 20, 2, 1, 0, 1, 1, 3, 1, 5 );
INSERT INTO weapon VALUES ( 44, 'Arrows (20)', '', 1, 1, 0, 0, 0, 0, 0, 3, 0, 1, 0, 5, 1, 0 );
INSERT INTO weapon VALUES ( 45, 'Blowgun needles (50)', '', 1, 1, 0, 0, 0, 0, 0, 3, 0, 1, 0, 5, 1, 0 );
INSERT INTO weapon VALUES ( 46, 'Crossbow bolts (20)', '', 1, 1.5, 0, 0, 0, 0, 0, 3, 0, 1, 0, 5, 1, 0 );
INSERT INTO weapon VALUES ( 47, 'Sling bullets (20)', '', 0.04, 1.5, 0, 0, 0, 0, 0, 3, 0, 1, 0, 5, 1, 0 );


INSERT INTO armor VALUES ( 1, 'Padded', 'Padded armor consists of quilted layers of cloth and batting.', 5, 8, 11, 0, 0, 0 );
INSERT INTO armor VALUES ( 2, 'Leather', 'The breastplate and shoulder protectors of this armor are made of leather that has been stiffened by being boiled in oil. The rest of the armor is made of softer and more flexible materials.', 10, 10, 11, 0, 0, 0 );
INSERT INTO armor VALUES ( 3, 'Studded leather', 'Made from tough but flexible leather, studded leather is reinforced with close-set rivets or spikes.', 45, 13, 12, 0, 0, 0 );
INSERT INTO armor VALUES ( 4, 'Hide', 'This crude armor consists of thick furs and pelts. It is commonly worn by barbarian tribes, evil humanoids, and other folk who lack access to the tools and materials needed to create better armor.', 10, 12, 12, 0, 1, 0 );
INSERT INTO armor VALUES ( 5, 'Chain shirt', 'Made of interlocking metal rings, a chain shirt is worn between layers of clothing or leather. This armor offers modest protection to the wearer''s upper body and allows the sound of the rings rubbing against one another to be muffled by outer layers.', 50, 20, 13, 0, 1, 0 );
INSERT INTO armor VALUES ( 6, 'Scale mail', 'This armor consists of a coat and leggings (and perhaps a separate skirt) of leather covered with overlapping pieces of metal, much like the scales of a fish. The suit includes gauntlets.', 50, 45, 14, 0, 1, 0 );
INSERT INTO armor VALUES ( 7, 'Breastplate', 'This armor consists of a fitted metal chest piece worn with supple leather. Although it leaves the legs and arms relatively unprotected, this armor provides good protection for the wearer''s vital organs while leaving the wearer relatively unencumbered.', 400, 20, 14, 0, 1, 0 );
INSERT INTO armor VALUES ( 8, 'Half plate', 'Half plate consists of shaped metal plates that cover most of the wearer''s body. It does not include leg protection beyond simple greaves that are attached with leather straps.', 750, 40, 15, 0, 1, 0 );
INSERT INTO armor VALUES ( 9, 'Ring mail', 'This armor is leather armor with heavy rings sewn into it. The rings help reinforce the armor against blows from swords and axes. Ring mail is inferior to chain mail, and it''s usually worn only by those who can''t afford better armor.', 30, 40, 14, 0, 2, 0 );
INSERT INTO armor VALUES ( 10, 'Chain mail', 'Made of interlocking metal rings, chain mail includes a layer of quilted fabric worn underneath the mail to prevent chafing and to cushion the impact of blows. The suit includes gauntlets.', 75, 55, 16, 0, 2, 0 );
INSERT INTO armor VALUES ( 11, 'Splint', 'This armor is made of narrow vertical strips of metal riveted to a backing of leather that is worn over cloth padding. Flexible chain mail protects the joints.', 200, 60, 17, 0, 2, 0 );
INSERT INTO armor VALUES ( 12, 'Plate', 'Plate consists of shaped, interlocking metal plates to cover the entire body. A suit of plate includes gauntlets, heavy leather boots, a visored helmet, and thick layers of padding underneath the armor. Buckles and straps distribute the weight over the body.', 1500, 65, 18, 0, 2, 0 );
INSERT INTO armor VALUES ( 13, 'Shield', 'A shield is made from wood or metal and is carried in one hand. Wielding a shield increases your Armor Class by 2. You can benefit from only one shield at a time.', 10, 6, 2, 0, 3, 0 );


INSERT INTO good VALUES (1, 'Abacus', '', 2, 2, 0, 0 );
INSERT INTO good VALUES (2, 'Acid (vial)', 'As an action, you can splash the contents of this vial onto a creature within 5 feet of you or throw the vial up to 20 feet, shattering it on impact. In either case, make a ranged attack against a creature or object, treating the acid as an improvised weapon. On a hit, the target takes 2d6 acid damage.', 25, 1, 1, 0 );
INSERT INTO good VALUES (3, 'Alchemist''s fire (flask)', 'This sticky, adhesive fluid ignites when exposed to air. As an action, you can throw this flask up to 20 feet, shattering it on impact. Make a ranged attack against a creature or object, treating the alchemist''s fire as an improvised weapon. On a hit, the target takes 1d4 fire damage at the start of each of its turns. A creature can end this damage by using its action to make a DC 10 Dexterity check to extinguish the flames.', 50, 1, 1, 0 );
INSERT INTO good VALUES (4, 'Antitoxin (vial)', 'A creature that drinks this vial of liquid gains advantage on saving throws against poison for 1 hour. It confers no benefit to undead or constructs.', 50, 0, 1, 0 );
INSERT INTO good VALUES (5, 'Arcane Focus - Crystal', 'An arcane focus is a special item--an orb, a crystal, a rod, a specially constructed staff, a wand-like length of wood, or some similar item--designed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use such an item as a spellcasting focus.', 10, 1, 0, 0 );
INSERT INTO good VALUES (6, 'Arcane Focus - Orb', 'An arcane focus is a special item--an orb, a crystal, a rod, a specially constructed staff, a wand-like length of wood, or some similar item--designed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use such an item as a spellcasting focus.', 20, 3, 0, 0 );
INSERT INTO good VALUES (7, 'Arcane Focus - Rod', 'An arcane focus is a special item--an orb, a crystal, a rod, a specially constructed staff, a wand-like length of wood, or some similar item--designed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use such an item as a spellcasting focus.', 10, 2, 0, 0 );
INSERT INTO good VALUES (8, 'Arcane Focus - Staff', 'An arcane focus is a special item--an orb, a crystal, a rod, a specially constructed staff, a wand-like length of wood, or some similar item--designed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use such an item as a spellcasting focus.', 5, 4, 0, 0 );
INSERT INTO good VALUES (9, 'Arcane Focus - Wand', 'An arcane focus is a special item--an orb, a crystal, a rod, a specially constructed staff, a wand-like length of wood, or some similar item--designed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use such an item as a spellcasting focus.', 10, 1, 0, 0 );
INSERT INTO good VALUES (10, 'Backpack', '', 2, 5, 0, 0 );
INSERT INTO good VALUES (11, 'Ball bearings (bag of 1,000)', 'As an action, you can spill these tiny metal balls from their pouch to cover a level, square area that is 10 feet on a side. A creature moving across the covered area must succeed on a DC 10 Dexterity saving throw or fall prone. A creature moving through the area at half speed doesn''t need to make the save.', 1, 2, 0, 0 );
INSERT INTO good VALUES (12, 'Barrel', '', 2, 70, 0, 0 );
INSERT INTO good VALUES (13, 'Basket', '', 0.4, 2, 0, 0 );
INSERT INTO good VALUES (14, 'Bedroll', '', 1, 7, 0, 0 );
INSERT INTO good VALUES (15, 'Bell', '', 1, 0, 0, 0 );
INSERT INTO good VALUES (16, 'Blanket', '', 0.5, 3, 0, 0 );
INSERT INTO good VALUES (17, 'Block and tackle', 'A set of pulleys with a cable threaded through them and a hook to attach to objects, a block and tackle allows you to hoist up to four times the weight you can normally lift.', 1, 5, 0, 0 );
INSERT INTO good VALUES (18, 'Book', 'A book might contain poetry, historical accounts, information pertaining to a particular field of lore, diagrams and notes on gnomish contraptions, or just about anything else that can be represented using text or pictures.', 25, 5, 0, 0 );
INSERT INTO good VALUES (19, 'Bottle, glass', '', 2, 2, 0, 0 );
INSERT INTO good VALUES (20, 'Bucket', '', 0.05, 2, 0, 0 );
INSERT INTO good VALUES (21, 'Caltrops (bag of 20)', 'As an action, you can spread a bag of caltrops to cover a square area that is 5 feet on a side. Any creature that enters the area must succeed on a DC 15 Dexterity saving throw or stop moving this turn and take 1 piercing damage. Taking this damage reduces the creature''s walking speed by 10 feet until the creature regains at least 1 hit point. A creature moving through the area at half speed doesn''t need to make the save.', 1, 2, 0, 0 );
INSERT INTO good VALUES (22, 'Candle', 'For 1 hour, a candle sheds bright light in a 5-foot radius and dim light for an additional 5 feet.', 0.01, 0, 0, 0 );
INSERT INTO good VALUES (23, 'Case, crossbow bolt', 'This wooden case can hold up to twenty crossbow bolts.', 1, 1, 0, 0 );
INSERT INTO good VALUES (24, 'Case, map or scroll', 'This cylindrical leather case can hold up to ten rolled-up sheets of paper or five rolled-up sheets of parchment.', 1, 1, 0, 0 );
INSERT INTO good VALUES (25, 'Chain (10 feet)', 'A chain has 10 hit points. It can be burst with a successful DC 20 Strength check.', 5, 10, 0, 0 );
INSERT INTO good VALUES (26, 'Chalk (1 piece)', '', 0.01, 0, 0, 0 );
INSERT INTO good VALUES (27, 'Chest', '', 5, 25, 0, 0 );
INSERT INTO good VALUES (28, 'Climber''s kit', 'A climber''s kit includes special pitons, boot tips, gloves, and a harness. You can use the climber''s kit as an action to anchor yourself, when you do, you can''t fall more than 25 feet from the point where you anchored yourself, and you can''t climb more than 25 feet away from that point without undoing the anchor.', 25, 12, 3, 0 );
INSERT INTO good VALUES (29, 'Clothes, common', '', 0.5, 3, 5, 0 );
INSERT INTO good VALUES (30, 'Clothes, costume', '', 5, 4, 5, 0 );
INSERT INTO good VALUES (31, 'Clothes, fine', '', 15, 6, 5, 0 );
INSERT INTO good VALUES (32, 'Clothes, traveler''s', '', 2, 4, 5, 0 );
INSERT INTO good VALUES (33, 'Component pouch', 'A component pouch is a small, watertight leather belt pouch that has compartments to hold all the material components and other special items you need to cast your spells, except for those components that have a specific cost (as indicated in a spell''s description).', 25, 2, 0, 0 );
INSERT INTO good VALUES (34, 'Crowbar', 'Using a crowbar grants advantage to Strength checks where the crowbar''s leverage can be applied.', 2, 5, 0, 0 );
INSERT INTO good VALUES (35, 'Druidic Focus - Sprig of mistletoe', 'A druidic focus might be a sprig of mistletoe or holly, a wand or scepter made of yew or another special wood, a staff drawn whole out of a living tree, or a totem object incorporating feathers, fur, bones, and teeth from sacred animals. A druid can use such an object as a spellcasting focus.', 1, 0, 0, 0 );
INSERT INTO good VALUES (36, 'Druidic Focus - Totem', 'A druidic focus might be a sprig of mistletoe or holly, a wand or scepter made of yew or another special wood, a staff drawn whole out of a living tree, or a totem object incorporating feathers, fur, bones, and teeth from sacred animals. A druid can use such an object as a spellcasting focus.', 1, 0, 0, 0 );
INSERT INTO good VALUES (37, 'Druidic Focus - Wooden staff', 'A druidic focus might be a sprig of mistletoe or holly, a wand or scepter made of yew or another special wood, a staff drawn whole out of a living tree, or a totem object incorporating feathers, fur, bones, and teeth from sacred animals. A druid can use such an object as a spellcasting focus.', 5, 4, 0, 0 );
INSERT INTO good VALUES (38, 'Druidic Focus - Yew wand', 'A druidic focus might be a sprig of mistletoe or holly, a wand or scepter made of yew or another special wood, a staff drawn whole out of a living tree, or a totem object incorporating feathers, fur, bones, and teeth from sacred animals. A druid can use such an object as a spellcasting focus.', 10, 1, 0, 0 );
INSERT INTO good VALUES (39, 'Fishing tackle', 'This kit includes a wooden rod, silken line, corkwood bobbers, steel hooks, lead sinkers, velvet lures, and narrow netting.', 1, 4, 3, 0 );
INSERT INTO good VALUES (40, 'Flask or tankard', '', 0.02, 1, 0, 0 );
INSERT INTO good VALUES (41, 'Grappling hook', '', 2, 4, 0, 0 );
INSERT INTO good VALUES (42, 'Hammer', '', 1, 3, 0, 0 );
INSERT INTO good VALUES (43, 'Hammer, sledge', '', 2, 10, 0, 0 );
INSERT INTO good VALUES (44, 'Healer''s kit', 'This kit is a leather pouch containing bandages, salves, and splints. The kit has ten uses. As an action, you can expend one use of the kit to stabilize a creature that has 0 hit points, without needing to make a Wisdom (Medicine) check.', 5, 3, 3, 0 );
INSERT INTO good VALUES (45, 'Holy Symbol - Amulet', 'A holy symbol is a representation of a god or pantheon. It might be an amulet depicting a symbol representing a deity, the same symbol carefully engraved or inlaid as an emblem on a shield, or a tiny box holding a fragment of a sacred relic. A cleric or paladin can use a holy symbol as a spellcasting focus. To use the symbol in this way, the caster must hold it in hand, wear it visibly, or bear it on a shield.', 5, 1, 0, 0 );
INSERT INTO good VALUES (46, 'Holy Symbol - Emblem', 'A holy symbol is a representation of a god or pantheon. It might be an amulet depicting a symbol representing a deity, the same symbol carefully engraved or inlaid as an emblem on a shield, or a tiny box holding a fragment of a sacred relic. A cleric or paladin can use a holy symbol as a spellcasting focus. To use the symbol in this way, the caster must hold it in hand, wear it visibly, or bear it on a shield.', 5, 0, 0, 0 );
INSERT INTO good VALUES (47, 'Holy Symbol - Reliquary', 'A holy symbol is a representation of a god or pantheon. It might be an amulet depicting a symbol representing a deity, the same symbol carefully engraved or inlaid as an emblem on a shield, or a tiny box holding a fragment of a sacred relic. A cleric or paladin can use a holy symbol as a spellcasting focus. To use the symbol in this way, the caster must hold it in hand, wear it visibly, or bear it on a shield.', 5, 2, 0, 0 );
INSERT INTO good VALUES (48, 'Holy water (flask)', 'As an action, you can splash the contents of this flask onto a creature within 5 feet of you or throw it up to 20 feet, shattering it on impact. In either case, make a ranged attack against a target creature, treating the holy water as an improvised weapon. If the target is a fiend or undead, it takes 2d6 radiant damage. A cleric or paladin may create holy water by performing a special ritual. The ritual takes 1 hour to perform, uses 25 gp worth of powdered silver, and requires the caster to expend a 1st-level spell slot.', 25, 1, 0, 0 );
INSERT INTO good VALUES (49, 'Hourglass', '', 25, 1, 0, 0 );
INSERT INTO good VALUES (50, 'Hunting trap', 'When you use your action to set it, this trap forms a saw-toothed steel ring that snaps shut when a creature steps on a pressure plate in the center. The trap is affixed by a heavy chain to an immobile object, such as a tree or a spike driven into the ground. A creature that steps on the plate must succeed on a DC 13 Dexterity saving throw or take 1d4 piercing damage and stop moving. Thereafter, until the creature breaks free of the trap, its movement is limited by the length of the chain (typically 3 feet long). A creature can use its action to make a DC 13 Strength check, freeing itself or another creature within its reach on a success. Each failed check deals 1 piercing damage to the trapped creature.', 5, 25, 0, 0 );
INSERT INTO good VALUES (51, 'Ink (1 ounce bottle)', '', 10, 0, 0, 0 );
INSERT INTO good VALUES (52, 'Ink pen', '', 0.02, 0, 0, 0 );
INSERT INTO good VALUES (53, 'Jug or pitcher', '', 0.02, 4, 0, 0 );
INSERT INTO good VALUES (54, 'Ladder (10 foot)', '', 0.1, 25, 0, 0 );
INSERT INTO good VALUES (55, 'Lamp', 'A lamp casts bright light in a 15-foot radius and dim light for an additional 30 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil.', 0.5, 1, 0, 0 );
INSERT INTO good VALUES (56, 'Lantern, bullseye', 'A bullseye lantern casts bright light in a 60-foot cone and dim light for an additional 60 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil.', 10, 2, 0, 0 );
INSERT INTO good VALUES (57, 'Lantern, hooded', 'A hooded lantern casts bright light in a 30-foot radius and dim light for an additional 30 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil. As an action, you can lower the hood, reducing the light to dim light in a 5-foot radius.', 5, 2, 0, 0 );
INSERT INTO good VALUES (58, 'Lock', 'A key is provided with the lock. Without the key, a creature proficient with thieves'' tools can pick this lock with a successful DC 15 Dexterity check. Your DM may decide that better locks are available for higher prices.', 10, 1, 0, 0 );
INSERT INTO good VALUES (59, 'Magnifying glass', 'This lens allows a closer look at small objects. It is also useful as a substitute for flint and steel when starting fires. Lighting a fire with a magnifying glass requires light as bright as sunlight to focus, tinder to ignite, and about 5 minutes for the fire to ignite. A magnifying glass grants advantage on any ability check made to appraise or inspect an item that is small or highly detailed.', 100, 0, 0, 0 );
INSERT INTO good VALUES (60, 'Manacles', 'These metal restraints can bind a Small or Medium creature. Escaping the manacles requires a successful DC 20 Dexterity check. Breaking them requires a successful DC 20 Strength check. Each set of manacles comes with one key. Without the key, a creature proficient with thieves'' tools can pick the manacles'' lock with a successful DC 15 Dexterity check. Manacles have 15 hit points.', 2, 6, 0, 0 );
INSERT INTO good VALUES (61, 'Mess kit', 'This tin box contains a cup and simple cutlery. The box clamps together, and one side can be used as a cooking pan and the other as a plate or shallow bowl.', 0.2, 1, 0, 0 );
INSERT INTO good VALUES (62, 'Mirror, steel', '', 5, 0.5, 0, 0 );
INSERT INTO good VALUES (63, 'Oil (flask)', 'Oil usually comes in a clay flask that holds 1 pint. As an action, you can splash the oil in this flask onto a creature within 5 feet of you or throw it up to 20 feet, shattering it on impact. Make a ranged attack against a target creature or object, treating the oil as an improvised weapon. On a hit, the target is covered in oil. If the target takes any fire damage before the oil dries (after 1 minute), the target takes an additional 5 fire damage from the burning oil. You can also pour a flask of oil on the ground to cover a 5-foot-square area, provided that the surface is level. If lit, the oil burns for 2 rounds and deals 5 fire damage to any creature that enters the area or ends its turn in the area. A creature can take this damage only once per turn.', 0.1, 1, 1, 0 );
INSERT INTO good VALUES (64, 'Paper (one sheet)', '', 0.2, 0, 0, 0 );
INSERT INTO good VALUES (65, 'Parchment (one sheet)', '', 0.1, 0, 0, 0 );
INSERT INTO good VALUES (66, 'Perfume (vial)', '', 5, 0, 1, 0 );
INSERT INTO good VALUES (67, 'Pick, miner''s', '', 2, 10, 0, 0 );
INSERT INTO good VALUES (68, 'Piton', '', 0.05, 0.25, 0, 0 );
INSERT INTO good VALUES (69, 'Poison, basic (vial)', 'You can use the poison in this vial to coat one slashing or piercing weapon or up to three pieces of ammunition. Applying the poison takes an action. A creature hit by the poisoned weapon or ammunition must make a DC 10 Constitution saving throw or take 1d4 poison damage. Once applied, the poison retains potency for 1 minute before drying.', 100, 0, 1, 0 );
INSERT INTO good VALUES (70, 'Pole (10-foot)', '', 0.05, 7, 0, 0 );
INSERT INTO good VALUES (71, 'Pot, iron', '', 2, 10, 0, 0 );
INSERT INTO good VALUES (72, 'Potion of healing', 'A character who drinks the magical red fluid in this vial regains 2d4 + 2 hit points. Drinking or administering a potion takes an action.', 50, 0.5, 1, 2 );
INSERT INTO good VALUES (73, 'Pouch', 'A cloth or leather pouch can hold up to 20 sling bullets or 50 blowgun needles, among other things. A compartmentalized pouch for holding spell components is called a component pouch (described earlier in this section).', 0.5, 1, 0, 0 );
INSERT INTO good VALUES (74, 'Quiver', 'A quiver can hold up to 20 arrows.', 1, 1, 0, 0 );
INSERT INTO good VALUES (75, 'Ram, portable', 'You can use a portable ram to break down doors. When doing so, you gain a +4 bonus on the Strength check. One other character can help you use the ram, giving you advantage on this check.', 4, 35, 0, 0 );
INSERT INTO good VALUES (76, 'Rations (1 day)', 'Rations consist of dry foods suitable for extended travel, including jerky, dried fruit, hardtack, and nuts.', 0.5, 2, 0, 0 );
INSERT INTO good VALUES (77, 'Robes', '', 1, 4, 5, 0 );
INSERT INTO good VALUES (78, 'Rope, hempen (50 feet)', 'Rope, whether made of hemp or silk, has 2 hit points and can be burst with a DC 17 Strength check.', 1, 10, 0, 0 );
INSERT INTO good VALUES (79, 'Rope, silk (50 feet)', 'Rope, whether made of hemp or silk, has 2 hit points and can be burst with a DC 17 Strength check.', 10, 5, 0, 0 );
INSERT INTO good VALUES (80, 'Sack', '', 0.01, 0.5, 0, 0 );
INSERT INTO good VALUES (81, 'Scale, merchant''s', 'A scale includes a small balance, pans, and a suitable assortment of weights up to 2 pounds. With it, you can measure the exact weight of small objects, such as raw precious metals or trade goods, to help determine their worth.', 5, 3, 0, 0 );
INSERT INTO good VALUES (82, 'Sealing wax', '', 0.5, 0, 0, 0 );
INSERT INTO good VALUES (83, 'Shovel', '', 2, 5, 0, 0 );
INSERT INTO good VALUES (84, 'Signal whistle', '', 0.5, 0, 0, 0 );
INSERT INTO good VALUES (85, 'Signet ring', '', 5, 0, 0, 0 );
INSERT INTO good VALUES (86, 'Soap', '', 0.2, 0, 0, 0 );
INSERT INTO good VALUES (87, 'Spellbook', 'Essential for wizards, a spellbook is a leather-bound tome with 100 blank vellum pages suitable for recording spells.', 50, 3, 2, 0 );
INSERT INTO good VALUES (88, 'Spikes, iron (10)', '', 1, 5, 0, 0 );
INSERT INTO good VALUES (89, 'Spyglass', 'Objects viewed through a spyglass are magnified to twice their size.', 1, 1, 0, 0 );
INSERT INTO good VALUES (90, 'Tent, two-person', 'A simple and portable canvas shelter, a tent sleeps two.', 2, 20, 0, 0 );
INSERT INTO good VALUES (91, 'Tinderbox', 'This small container holds flint, fire steel, and tinder (usually dry cloth soaked in light oil) used to kindle a fire. Using it to light a torch--or anything else with abundant, exposed fuel--takes an action. Lighting any other fire takes 1 minute.', 0.5, 1, 0, 0 );
INSERT INTO good VALUES (92, 'Torch', 'A torch burns for 1 hour, providing bright light in a 20-foot radius and dim light for an additional 20 feet. If you make a melee attack with a burning torch and hit, it deals 1 fire damage.', 0.01, 1, 0, 0 );
INSERT INTO good VALUES (93, 'Vial', '', 1, 0, 0, 0 );
INSERT INTO good VALUES (94, 'Waterskin', '', 0.2, 5, 0, 0 );
INSERT INTO good VALUES (95, 'Whetstone', '', 0.01, 1, 0, 0 );
INSERT INTO good VALUES (96, 'Alchemist''s supplies', '', 50, 8, 3, 0 );
INSERT INTO good VALUES (97, 'Brewer''s supplies', '', 20, 9, 3, 0 );
INSERT INTO good VALUES (98, 'Calligrapher''s supplies', '', 10, 5, 3, 0 );
INSERT INTO good VALUES (99, 'Carpenter''s tools', '', 8, 6, 3, 0 );
INSERT INTO good VALUES (100, 'Cartographer''s tools', '', 15, 6, 3, 0 );
INSERT INTO good VALUES (101, 'Cobbler''s tools', '', 5, 5, 3, 0 );
INSERT INTO good VALUES (102, 'Cook''s utensils', '', 1, 8, 3, 0 );
INSERT INTO good VALUES (103, 'Glassblower''s tools', '', 30, 5, 3, 0 );
INSERT INTO good VALUES (104, 'Jeweler''s tools', '', 25, 2, 3, 0 );
INSERT INTO good VALUES (105, 'Leatherworker''s tools', '', 5, 5, 3, 0 );
INSERT INTO good VALUES (106, 'Mason''s tools', '', 10, 8, 3, 0 );
INSERT INTO good VALUES (107, 'Painter''s supplies', '', 10, 5, 3, 0 );
INSERT INTO good VALUES (108, 'Potter''s tools', '', 10, 3, 3, 0 );
INSERT INTO good VALUES (109, 'Smith''s tools', '', 20, 8, 3, 0 );
INSERT INTO good VALUES (110, 'Tinker''s tools', '', 50, 10, 3, 0 );
INSERT INTO good VALUES (111, 'Weaver''s tools', '', 1, 5, 3, 0 );
INSERT INTO good VALUES (112, 'Woodcarver''s tools', '', 1, 5, 3, 0 );
INSERT INTO good VALUES (113, 'Dice set', '', 0.1, 0, 0, 0 );
INSERT INTO good VALUES (114, 'Dragonchess set', '', 1, 0.5, 0, 0 );
INSERT INTO good VALUES (115, 'Playing card set', '', 0.5, 0, 0, 0 );
INSERT INTO good VALUES (116, 'Three-Dragon Ante set', '', 1, 0, 0, 0 );
INSERT INTO good VALUES (117, 'Bagpipes', '', 30, 6, 8, 0 );
INSERT INTO good VALUES (118, 'Drum', '', 6, 3, 8, 0 );
INSERT INTO good VALUES (119, 'Dulcimer', '', 25, 10, 8, 0 );
INSERT INTO good VALUES (120, 'Flute', '', 2, 1, 8, 0 );
INSERT INTO good VALUES (121, 'Lute', '', 35, 2, 8, 0 );
INSERT INTO good VALUES (122, 'Lyre', '', 30, 2, 8, 0 );
INSERT INTO good VALUES (123, 'Horn', '', 3, 2, 8, 0 );
INSERT INTO good VALUES (124, 'Pan flute', '', 12, 2, 8, 0 );
INSERT INTO good VALUES (125, 'Shawm', '', 2, 1, 8, 0 );
INSERT INTO good VALUES (126, 'Viol', '', 30, 1, 8, 0 );
INSERT INTO good VALUES (127, 'Disguise kit', 'This pouch of cosmetics, hair dye, and small props lets you create disguises that change your physical appearance. Proficiency with this kit lets you add your proficiency bonus to any ability checks you make to create a visual disguise.', 25, 3, 3, 0 );
INSERT INTO good VALUES (128, 'Forgery kit', 'This small box contains a variety of papers and parchments, pens and inks, seals and sealing wax, gold and silver leaf, and other supplies necessary to create convincing forgeries of physical documents. Proficiency with this kit lets you add your proficiency bonus to any ability checks you make to create a physical forgery of a document.', 15, 5, 3, 0 );
INSERT INTO good VALUES (129, 'Herbalism kit', 'This kit contains a variety of instruments such as clippers, mortar and pestle, and pouches and vials used by herbalists to create remedies and potions. Proficiency with this kit lets you add your proficiency bonus to any ability checks you make to identify or apply herbs. Also, proficiency with this kit is required to create antitoxin and potions of healing.', 5, 3, 3, 0 );
INSERT INTO good VALUES (130, 'Navigator''s tools', 'This set of instruments is used for navigation at sea. Proficiency with navigator''s tools lets you chart a ship''s course and follow navigation charts. In addition, these tools allow you to add your proficiency bonus to any ability check you make to avoid getting lost at sea.', 25, 2, 3, 0 );
INSERT INTO good VALUES (131, 'Poisoner''s kit', 'A poisoner''s kit includes the vials, chemicals, and other equipment necessary for the creation of poisons. Proficiency with this kit lets you add your proficiency bonus to any ability checks you make to craft or use poisons.', 50, 2, 3, 0 );
INSERT INTO good VALUES (132, 'Thieves'' tools', 'This set of tools includes a small file, a set of lock picks, a small mirror mounted on a metal handle, a set of narrow-bladed scissors, and a pair of pliers. Proficiency with these tools lets you add your proficiency bonus to any ability checks you make to disarm traps or open locks.', 25, 1, 3, 0 );
INSERT INTO good VALUES (133, 'Camel', '', 50, 0, 6, 0 );
INSERT INTO good VALUES (134, 'Donkey or mule', '', 8, 0, 6, 0 );
INSERT INTO good VALUES (135, 'Elephant', '', 200, 0, 6, 0 );
INSERT INTO good VALUES (136, 'Horse, draft', '', 50, 0, 6, 0 );
INSERT INTO good VALUES (137, 'Horse, riding', '', 75, 0, 6, 0 );
INSERT INTO good VALUES (138, 'Mastiff', '', 25, 0, 6, 0 );
INSERT INTO good VALUES (139, 'Pony', '', 30, 0, 6, 0 );
INSERT INTO good VALUES (140, 'Warhorse', '', 400, 0, 6, 0 );
INSERT INTO good VALUES (141, 'Barding', '', 1600, 0, 7, 0 );
INSERT INTO good VALUES (142, 'Bit and bridle', '', 2, 0, 7, 0 );
INSERT INTO good VALUES (143, 'Carriage', '', 100, 0, 6, 0 );
INSERT INTO good VALUES (144, 'Cart', '', 15, 0, 6, 0 );
INSERT INTO good VALUES (145, 'Chariot', '', 250, 0, 6, 0 );
INSERT INTO good VALUES (146, 'Saddle, Exotic', '', 60, 0, 7, 0 );
INSERT INTO good VALUES (147, 'Saddle, Military', '', 20, 0, 7, 0 );
INSERT INTO good VALUES (148, 'Saddle, Pack', '', 5, 0, 7, 0 );
INSERT INTO good VALUES (149, 'Saddle, Riding', '', 10, 0, 7, 0 );
INSERT INTO good VALUES (150, 'Saddlebags', '', 4, 0, 7, 0 );
INSERT INTO good VALUES (151, 'Sled', '', 20, 0, 6, 0 );
INSERT INTO good VALUES (152, 'Wagon', '', 35, 0, 6, 0 );
INSERT INTO good VALUES (153, 'Galley', '', 30000, 0, 6, 0 );
INSERT INTO good VALUES (154, 'Keelboat', '', 3000, 0, 6, 0 );
INSERT INTO good VALUES (155, 'Longship', '', 10000, 0, 6, 0 );
INSERT INTO good VALUES (156, 'Rowboat', '', 50, 0, 6, 0 );
INSERT INTO good VALUES (157, 'Sailing ship', '', 10000, 0, 6, 0 );
INSERT INTO good VALUES (158, 'Warship', '', 25000, 0, 6, 0 );
