INSERT INTO feat VALUES ( 1, 'Actor', '', '+1 in Cha, advantage on Deception and Performance checks, mimic the speech of a person or the sounds made by a creature.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 2, 'Alert', '', '+5 to initiative, you can''t be surprised, and creatures you don''t see don''t gain advantage on attack roll against you.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 3, 'Athlete', '', '+1 in Str or Dex, you stand up and climb more quickly, and you can jump with only a 5-ft run.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 4, 'Charger', '', 'As part of the Dash action you can make a melee attack with a +5 bonus if you move at least 10 ft before.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 5, 'Crossbow Expert', '', 'You ignore the loading property of crossbows and don''t have disadvantage for being in contact with a creature when you shoot.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 6, 'Defensive Duelist', 'Dexterity 13 or higher', 'You can add you proficiency bonus to your AC if you are wielding a finesse weapon.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 7, 'Dual Wielder', '', '+1 to CA if you''re wielding a melee weapon in each hand, two-weapon fighting with non-light weapon, draw two weapons.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 8, 'Dungeon Delver', '', 'Advantage to Perception and Investigation checks, to saving throws vs traps, and search for traps at normal pace.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 9, 'Durable', '', '+1 in Con and for each Hit Dice you regain a minimum of hit points equals to 2 x your Constitution modifier.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 10, 'Elemental Adept', 'The ability to cast at least one spell', 'Your spells ignore resistance to a damage type (acid, cold, fire, lightning, or thunder) and treat any 1 in damage as a 2.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 11, 'Grappler', 'Strength 13 or higher', 'You have advantage on attack rolls when grappling, and can try to restrained a creature grappled by you.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 12, 'Great Weapon Master', '', 'Extra attack after a melee critical hit and you can choose to take -5 to attack roll to add +10 to damage with an heavy weapon.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 13, 'Healer', '', 'You can stabilize a creature and restore it to 1 hp, or restore [1d6+4+its number of Hit Dice] hp to it.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 14, 'Heavily Armored', 'Proficiency with medium armor', '+1 in Str and you gain proficiency with heavy armor.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 15, 'Heavy Armor Master', 'Proficiency with heavy armor', '+1 in Str and bludgeoning, piercing, and slashing damage are reduced by 3 if you are wearing an heavy armor.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 16, 'Inspiring Leader', 'Charisma 13 or higher', 'Up to 6 creatures within 30 ft of you can gain temporary hp equal to your level + your Cha modifier.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 17, 'Keen Mind', '', '+1 in Int, you know which way is north, when is the next sunrise/sunset, and recall any events within the past month.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 18, 'Lightly Armored', '', '+1 in Str or Dex and you gain profociency with light armor.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 19, 'Linguist', '', '+1 in Int, you learn three languages, and you can ably create ciphers.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 20, 'Lucky', '', 'You can reroll one d20 or force to reroll an attack roll against you (3/long rest).', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 21, 'Mage Slayer', '', 'You can use a reaction to make a melee attack against a spellcaster and advantage on saving throws against spell within 5 ft.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 22, 'Magic Initiate', '', 'You learn two cantrips and one 1st-level spell from one class.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 23, 'Martial Adept', '', 'You learn two maneuvers from Battle Master archetype and gain one superiority die (d6).', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 24, 'Medium Armor Master', 'Proficiency with medium armor', 'No disadvantage to Stealth checks wearing medium armor and Dexterity bonus max to +3 instead of +2.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 25, 'Mobile', '', 'Your speed increase by 10 ft, you can Dash on difficult terrain without malus, and don''t provoke opportunity attacks in melee.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 26, 'Moderately Armored', 'Proficiency with light armor', '+1 in Str or Dex and you gain proficiency with medium armor and shields.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 27, 'Mounted Combatant', '', 'Advantage on melee attacks against unmounted creature and force an attack to target you instead of your mount.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 28, 'Observant', '', '+1 in Int or Wis, you can read on lips, and you have a +5 bonus in passive Perception and passive Investigation.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 29, 'Polearm Master', '', 'You can make an extra attack with a polearm weapon, and make an opportunity attack if a creature enter your reach.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 30, 'Resilient', '', '+1 in one ability and you gain proficiency in saving throws using this ability.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 31, 'Ritual Caster', 'Intelligence or Wisdom 13 or higher', 'You have a ritual book with two 1-st level ritual spells from one class and you can later on add other ritual spells you found.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 32, 'Savage Attacker', '', 'You can reroll melee weapon attack damage once per turn.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 33, 'Sentinel', '', 'A successful OA reduce creature''s speed to 0 for this turn and possibility to make an OA even if the ennemy take Disengage.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 34, 'Sharpshooter', '', 'Your ranged attacks ignore some cover, no disavantage at long range, and possibility to take -5 to hit for +10 on ranged damage.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 35, 'Shield Master', '', 'Attack also allows to shove, shield bonus to Dex saving throws againts spells, and no 1/2 damage on successful saving throw.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 36, 'Skilled', '', 'You gain proliciency with three skills or tools.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 37, 'Skulker', 'Dexterity 13 or higher', 'Ranged weapon attack doesn''t reveal your position and possibility to hide in a lighlly obscured area.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 38, 'Spell Sniper', 'The ability to cast at least one spell', 'Offensive spell''s range doubled, these spells ignore some cover, and you learn one offensive cantrip.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 39, 'Tavern Brawler', '', '+1 in Str or Con, proficiency with improvised weapons, d4 for unarmed strike, and grapple with a bonus action.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 40, 'Tough', '', 'Your hit point maximum increases by an amount equal to twice your level then by +2 at each level.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 41, 'War Caster', 'The ability to cast at least one spell', 'You have advantage on saving throws to maintain concentration and you can cast some spells as part of an OA with a reaction.', 0, 0, 0, 0, 0 );
INSERT INTO feat VALUES ( 42, 'Weapon Master', '', '+1 in Str or Dex and you gain proficiency with four weapons.', 0, 0, 0, 0, 0 );
