UPDATE race SET image_id = 22 WHERE id = 1;
UPDATE race SET image_id = 25 WHERE id = 2;
UPDATE race SET image_id = 6 WHERE id = 3;
UPDATE race SET image_id = 10 WHERE id = 4;
UPDATE race SET image_id = 12 WHERE id = 5;
UPDATE race SET image_id = 16 WHERE id = 6;
UPDATE race SET image_id = 32 WHERE id = 7;
UPDATE race SET image_id = 14 WHERE id = 8;
UPDATE race SET image_id = 39 WHERE id = 9;
