UPDATE armor_text SET description = 'Player''s Handbook page 125' WHERE armor_id = 0 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 125' WHERE armor_id = 1 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 126' WHERE armor_id = 2 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 124' WHERE armor_id = 3 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 125' WHERE armor_id = 4 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 125' WHERE armor_id = 5 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 124' WHERE armor_id = 6 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 124' WHERE armor_id = 7 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 126' WHERE armor_id = 8 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 124' WHERE armor_id = 9 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 125' WHERE armor_id = 10 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 124' WHERE armor_id = 11 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 124' WHERE armor_id = 12 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 125' WHERE armor_id = 13 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 125' WHERE armor_id = 14 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 125' WHERE armor_id = 15 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 125' WHERE armor_id = 16 AND language_id = 0;
UPDATE armor_text SET description = 'Player''s Handbook page 125' WHERE armor_id = 17 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 219' WHERE armor_id = 18 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 220' WHERE armor_id = 19 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 220' WHERE armor_id = 20 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 220' WHERE armor_id = 21 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 220' WHERE armor_id = 22 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 220' WHERE armor_id = 23 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 220' WHERE armor_id = 24 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 220' WHERE armor_id = 25 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 220' WHERE armor_id = 26 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 220' WHERE armor_id = 27 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 220' WHERE armor_id = 28 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 220' WHERE armor_id = 29 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 221' WHERE armor_id = 30 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 221' WHERE armor_id = 31 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 221' WHERE armor_id = 32 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 221' WHERE armor_id = 33 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 221' WHERE armor_id = 34 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 221' WHERE armor_id = 35 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 221' WHERE armor_id = 36 AND language_id = 0;
UPDATE armor_text SET description = 'Dungeon Master''s Guide page 221' WHERE armor_id = 37 AND language_id = 0;

UPDATE armor_text SET description = 'Spieler Handbuch Seite 152' WHERE armor_id = 0 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 150' WHERE armor_id = 1 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 149' WHERE armor_id = 2 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 149' WHERE armor_id = 3 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 149' WHERE armor_id = 4 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 151' WHERE armor_id = 5 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 149' WHERE armor_id = 6 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 149' WHERE armor_id = 7 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 151' WHERE armor_id = 8 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 149' WHERE armor_id = 9 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 150' WHERE armor_id = 10 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 150' WHERE armor_id = 11 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 151' WHERE armor_id = 12 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 150' WHERE armor_id = 13 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 150' WHERE armor_id = 14 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 151' WHERE armor_id = 15 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 151' WHERE armor_id = 16 AND language_id = 1;
UPDATE armor_text SET description = 'Spieler Handbuch Seite 152' WHERE armor_id = 17 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 272' WHERE armor_id = 18 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 273' WHERE armor_id = 19 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 272' WHERE armor_id = 20 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 272' WHERE armor_id = 21 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 273' WHERE armor_id = 22 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 273' WHERE armor_id = 23 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 274' WHERE armor_id = 24 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 273' WHERE armor_id = 25 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 273' WHERE armor_id = 26 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 273' WHERE armor_id = 27 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 274' WHERE armor_id = 28 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 273' WHERE armor_id = 29 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 274' WHERE armor_id = 30 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 274' WHERE armor_id = 31 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 274' WHERE armor_id = 32 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 274' WHERE armor_id = 33 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 274' WHERE armor_id = 34 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 274' WHERE armor_id = 35 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 274' WHERE armor_id = 36 AND language_id = 1;
UPDATE armor_text SET description = 'Spielleiter Handbuch Seite 274' WHERE armor_id = 37 AND language_id = 1;
