UPDATE race_trait SET trait_id = 24 WHERE trait_id = 38;
DELETE FROM trait_text WHERE trait_id = 38;
DELETE FROM trait WHERE id = 38;

UPDATE trait_text SET name = 'Extra Feet' WHERE trait_id = 0 AND language_id = 0;
UPDATE trait_text SET name = 'Extra Skill Points' WHERE trait_id = 1 AND language_id = 0;
UPDATE trait_text SET name = 'Ability Adjustment (+2 Con, -2 Cha)' WHERE trait_id = 2 AND language_id = 0;
UPDATE trait_text SET name = 'Darkvision (60 feet)' WHERE trait_id = 3 AND language_id = 0;
UPDATE trait_text SET name = 'Carry Heavy Load' WHERE trait_id = 4 AND language_id = 0;
UPDATE trait_text SET name = 'Stonecunning' WHERE trait_id = 5 AND language_id = 0;
UPDATE trait_text SET name = 'Weapon Familiarity (Dwarf)' WHERE trait_id = 6 AND language_id = 0;
UPDATE trait_text SET name = 'Stability' WHERE trait_id = 7 AND language_id = 0;
UPDATE trait_text SET name = 'Resist Poison' WHERE trait_id = 8 AND language_id = 0;
UPDATE trait_text SET name = 'Resist Spells' WHERE trait_id = 9 AND language_id = 0;
UPDATE trait_text SET name = 'Animosity (Orcs and Goblinoids)' WHERE trait_id = 10 AND language_id = 0;
UPDATE trait_text SET name = 'Armor Bonus (Giants)' WHERE trait_id = 11 AND language_id = 0;
UPDATE trait_text SET name = 'Skill Bonus (Appraise stone or metal)' WHERE trait_id = 12 AND language_id = 0;
UPDATE trait_text SET name = 'Skill Bonus (Craft stone or metal)' WHERE trait_id = 13 AND language_id = 0;
UPDATE trait_text SET name = 'Ability Adjustment (+2 Dex, -2 Con)' WHERE trait_id = 14 AND language_id = 0;
UPDATE trait_text SET name = 'Resist Sleep' WHERE trait_id = 15 AND language_id = 0;
UPDATE trait_text SET name = 'Low-Light Vision' WHERE trait_id = 16 AND language_id = 0;
UPDATE trait_text SET name = 'Weapon Proficiency (Sword and Bow)' WHERE trait_id = 17 AND language_id = 0;
UPDATE trait_text SET name = 'Skill Bonus (Listen, Search, Spot)' WHERE trait_id = 18 AND language_id = 0;
UPDATE trait_text SET name = 'Ability Adjustment (+2 Con, -2 Str)' WHERE trait_id = 19 AND language_id = 0;
UPDATE trait_text SET name = 'Weapon Familiarity (Gnome)' WHERE trait_id = 20 AND language_id = 0;
UPDATE trait_text SET name = 'Resist Illusion' WHERE trait_id = 21 AND language_id = 0;
UPDATE trait_text SET name = 'Improved Illusion' WHERE trait_id = 22 AND language_id = 0;
UPDATE trait_text SET name = 'Animosity (Kobolds and Goblinoids)' WHERE trait_id = 23 AND language_id = 0;
UPDATE trait_text SET name = 'Skill Bonus (Listen)' WHERE trait_id = 24 AND language_id = 0;
UPDATE trait_text SET name = 'Skill Bonus (Alchemy)' WHERE trait_id = 25 AND language_id = 0;
UPDATE trait_text SET name = 'Spell Bonus (Speak with Animal)' WHERE trait_id = 26 AND language_id = 0;
UPDATE trait_text SET name = 'Spell Bonus (Illusion)' WHERE trait_id = 27 AND language_id = 0;
UPDATE trait_text SET name = 'Skill Bonus, lesser (Listen, Search, Spot)' WHERE trait_id = 28 AND language_id = 0;
UPDATE trait_text SET name = 'Skill Bonus (Diplomacy, Gather Information)' WHERE trait_id = 29 AND language_id = 0;
UPDATE trait_text SET name = 'Elven Blood' WHERE trait_id = 30 AND language_id = 0;
UPDATE trait_text SET name = 'Ability Adjustment (+2 Str, -2 Int, -2 Cha)' WHERE trait_id = 31 AND language_id = 0;
UPDATE trait_text SET name = 'Orc Blood' WHERE trait_id = 32 AND language_id = 0;
UPDATE trait_text SET name = 'Ability Adjustment (+2 Dex, -2 Str)' WHERE trait_id = 33 AND language_id = 0;
UPDATE trait_text SET name = 'Skill Bonus (Climb, Jump, Move Silently)' WHERE trait_id = 34 AND language_id = 0;
UPDATE trait_text SET name = 'Resist Misfortune, lesser' WHERE trait_id = 35 AND language_id = 0;
UPDATE trait_text SET name = 'Resist Fear' WHERE trait_id = 36 AND language_id = 0;
UPDATE trait_text SET name = 'Weapon Proficiency (Thrown Weapons and Slings)' WHERE trait_id = 37 AND language_id = 0;
UPDATE trait_text SET name = 'Resist Spells, greater' WHERE trait_id = 39 AND language_id = 0;
UPDATE trait_text SET name = 'Resist Poison, greater' WHERE trait_id = 40 AND language_id = 0;
UPDATE trait_text SET name = 'Darkvision (90 feet)' WHERE trait_id = 41 AND language_id = 0;
UPDATE trait_text SET name = 'Light Sensitivity' WHERE trait_id = 42 AND language_id = 0;
UPDATE trait_text SET name = 'Ability Adjustment (+2 Con, -4 Cha)' WHERE trait_id = 43 AND language_id = 0;
UPDATE trait_text SET name = 'Darkvision (120 feet)' WHERE trait_id = 44 AND language_id = 0;
UPDATE trait_text SET name = 'Immunity' WHERE trait_id = 45 AND language_id = 0;
UPDATE trait_text SET name = 'Spell Bonus (Duergar)' WHERE trait_id = 46 AND language_id = 0;
UPDATE trait_text SET name = 'Skill Bonus (Move Silently)' WHERE trait_id = 47 AND language_id = 0;
UPDATE trait_text SET name = 'Skill Bonus (Listen and Spot)' WHERE trait_id = 48 AND language_id = 0;
UPDATE trait_text SET name = 'Ability Adjustment (+2 Dex, -2 Int)' WHERE trait_id = 49 AND language_id = 0;
UPDATE trait_text SET name = 'Gills' WHERE trait_id = 50 AND language_id = 0;
UPDATE trait_text SET name = 'Superior Low-Light Vision' WHERE trait_id = 51 AND language_id = 0;
UPDATE trait_text SET name = 'Poison' WHERE trait_id = 52 AND language_id = 0;
UPDATE trait_text SET name = 'Ability Adjustment (+2 Int, +2 Cha)' WHERE trait_id = 53 AND language_id = 0;
UPDATE trait_text SET name = 'Spell Resistance' WHERE trait_id = 54 AND language_id = 0;
UPDATE trait_text SET name = 'Spell Bonus (Drow)' WHERE trait_id = 55 AND language_id = 0;
UPDATE trait_text SET name = 'Weapon Proficiency (Sword and Crossbow)' WHERE trait_id = 56 AND language_id = 0;
UPDATE trait_text SET name = 'Light Blindness' WHERE trait_id = 57 AND language_id = 0;
UPDATE trait_text SET name = 'Ability Adjustment (+2 Int, -2 Str)' WHERE trait_id = 58 AND language_id = 0;
UPDATE trait_text SET name = 'Ability Adjustment (+2 Dex, -2 Int)' WHERE trait_id = 59 AND language_id = 0;
UPDATE trait_text SET name = 'Ability Adjustment (+2 Str, -2 Int)' WHERE trait_id = 60 AND language_id = 0;
UPDATE trait_text SET name = 'Ability Adjustment (-2 Str, +2 Dex, +2 Wis, -4 Cha)' WHERE trait_id = 61 AND language_id = 0;
UPDATE trait_text SET name = 'Resist Misfortune' WHERE trait_id = 62 AND language_id = 0;
UPDATE trait_text SET name = 'Spell Bonus (Svirfneblin)' WHERE trait_id = 63 AND language_id = 0;
UPDATE trait_text SET name = 'Spell Bonus (Nondetection)' WHERE trait_id = 64 AND language_id = 0;
UPDATE trait_text SET name = 'Skill Bonus (Hide)' WHERE trait_id = 65 AND language_id = 0;
UPDATE trait_text SET name = 'Spell Bonus (Forest Gnome)' WHERE trait_id = 66 AND language_id = 0;
UPDATE trait_text SET name = 'Animosity (Kobolds, Goblinoids, Orcs and Reptilian)' WHERE trait_id = 67 AND language_id = 0;
UPDATE trait_text SET name = 'Skill Bonus, greater (Hide)' WHERE trait_id = 68 AND language_id = 0;
UPDATE trait_text SET name = 'Skill Bonus (Search, Spot, Listen)' WHERE trait_id = 69 AND language_id = 0;

UPDATE trait_text SET name = 'Extra Talent' WHERE trait_id = 0 AND language_id = 1;
UPDATE trait_text SET name = 'Extra Fertigkeitspunkte' WHERE trait_id = 1 AND language_id = 1;
UPDATE trait_text SET name = 'Attributsanpassung (+2 KO, -2 CH)' WHERE trait_id = 2 AND language_id = 1;
UPDATE trait_text SET name = 'Dunkelsicht (18m)' WHERE trait_id = 3 AND language_id = 1;
UPDATE trait_text SET name = 'Schwere Lasten Tragen' WHERE trait_id = 4 AND language_id = 1;
UPDATE trait_text SET name = 'Steinwissen' WHERE trait_id = 5 AND language_id = 1;
UPDATE trait_text SET name = 'Waffenvertrautheit (Zwerg)' WHERE trait_id = 6 AND language_id = 1;
UPDATE trait_text SET name = 'Standfestigkeit' WHERE trait_id = 7 AND language_id = 1;
UPDATE trait_text SET name = 'Giften Widerstehen' WHERE trait_id = 8 AND language_id = 1;
UPDATE trait_text SET name = 'Zaubern Widerstehen' WHERE trait_id = 9 AND language_id = 1;
UPDATE trait_text SET name = 'Feindseligkeit (Orks und Goblinoiden)' WHERE trait_id = 10 AND language_id = 1;
UPDATE trait_text SET name = 'Ruestungsbonus (Riesen)' WHERE trait_id = 11 AND language_id = 1;
UPDATE trait_text SET name = 'Fertigkeitsbonus (Schaetzen Stein oder Metall)' WHERE trait_id = 12 AND language_id = 1;
UPDATE trait_text SET name = 'Fertigkeitsbonus (Handwerk Stein oder Metall)' WHERE trait_id = 13 AND language_id = 1;
UPDATE trait_text SET name = 'Attributsanpassung (+2 GE, -2 KO)' WHERE trait_id = 14 AND language_id = 1;
UPDATE trait_text SET name = 'Schlaf Widerstehen' WHERE trait_id = 15 AND language_id = 1;
UPDATE trait_text SET name = 'Daemmersicht' WHERE trait_id = 16 AND language_id = 1;
UPDATE trait_text SET name = 'Umgang mit Waffen (Schwert und Bogen)' WHERE trait_id = 17 AND language_id = 1;
UPDATE trait_text SET name = 'Fertigkeitsbonus (Lauschen, Suchen, Entdecken)' WHERE trait_id = 18 AND language_id = 1;
UPDATE trait_text SET name = 'Attributsanpassung (+2 KO, -2 ST)' WHERE trait_id = 19 AND language_id = 1;
UPDATE trait_text SET name = 'Waffenvertrautheit (Gnom)' WHERE trait_id = 20 AND language_id = 1;
UPDATE trait_text SET name = 'Illusion Widerstehen' WHERE trait_id = 21 AND language_id = 1;
UPDATE trait_text SET name = 'Verbesserte Illusion' WHERE trait_id = 22 AND language_id = 1;
UPDATE trait_text SET name = 'Feindseligkeit (Kobolde und Goblinoiden)' WHERE trait_id = 23 AND language_id = 1;
UPDATE trait_text SET name = 'Fertigkeitsbonus (Lauschen)' WHERE trait_id = 24 AND language_id = 1;
UPDATE trait_text SET name = 'Fertigkeitsbonus (Alchemie)' WHERE trait_id = 25 AND language_id = 1;
UPDATE trait_text SET name = 'Zauberbonus (Mit Tieren sprechen)' WHERE trait_id = 26 AND language_id = 1;
UPDATE trait_text SET name = 'Zauberbonus (Illusion)' WHERE trait_id = 27 AND language_id = 1;
UPDATE trait_text SET name = 'Fertigkeitsbonus, geringer (Lauschen, Suchen, Entdecken)' WHERE trait_id = 28 AND language_id = 1;
UPDATE trait_text SET name = 'Fertigkeitsbonus (Diplomatie, Informationen sammeln)' WHERE trait_id = 29 AND language_id = 1;
UPDATE trait_text SET name = 'Elfenblut' WHERE trait_id = 30 AND language_id = 1;
UPDATE trait_text SET name = 'Attributsanpassung (+2 ST, -2 IN, -2 CH)' WHERE trait_id = 31 AND language_id = 1;
UPDATE trait_text SET name = 'Orkblut' WHERE trait_id = 32 AND language_id = 1;
UPDATE trait_text SET name = 'Attributsanpassung (+2 GE, -2 ST)' WHERE trait_id = 33 AND language_id = 1;
UPDATE trait_text SET name = 'Fertigkeitsbonus (Klettern, Springen, Leise bewegen)' WHERE trait_id = 34 AND language_id = 1;
UPDATE trait_text SET name = 'Unglueck Widerstehen, geringer' WHERE trait_id = 35 AND language_id = 1;
UPDATE trait_text SET name = 'Angst Widerstehen' WHERE trait_id = 36 AND language_id = 1;
UPDATE trait_text SET name = 'Umgang mit Waffen (Wurfwaffen und Schleuder)' WHERE trait_id = 37 AND language_id = 1;
UPDATE trait_text SET name = 'Zaubern Widerstehen, geringer' WHERE trait_id = 39 AND language_id = 1;
UPDATE trait_text SET name = 'Giften Widerstehen, geringer' WHERE trait_id = 40 AND language_id = 1;
UPDATE trait_text SET name = 'Dunkelsicht (24m)' WHERE trait_id = 41 AND language_id = 1;
UPDATE trait_text SET name = 'Lichtempfindlichkeit' WHERE trait_id = 42 AND language_id = 1;
UPDATE trait_text SET name = 'Attributsanpassung (+2 KO, -4 CH)' WHERE trait_id = 43 AND language_id = 1;
UPDATE trait_text SET name = 'Dunkelsicht (30m)' WHERE trait_id = 44 AND language_id = 1;
UPDATE trait_text SET name = 'Immunitaet' WHERE trait_id = 45 AND language_id = 1;
UPDATE trait_text SET name = 'Zauberbonus (Grauzwerg)' WHERE trait_id = 46 AND language_id = 1;
UPDATE trait_text SET name = 'Fertigkeitsbonus (Leise bewegen)' WHERE trait_id = 47 AND language_id = 1;
UPDATE trait_text SET name = 'Fertigkeitsbonus (Lauschen, Entdecken)' WHERE trait_id = 48 AND language_id = 1;
UPDATE trait_text SET name = 'Attributsanpassung (+2 GE, -2 IN)' WHERE trait_id = 49 AND language_id = 1;
UPDATE trait_text SET name = 'Kiemen' WHERE trait_id = 50 AND language_id = 1;
UPDATE trait_text SET name = 'Ueberlegene Daemmersicht' WHERE trait_id = 51 AND language_id = 1;
UPDATE trait_text SET name = 'Gift' WHERE trait_id = 52 AND language_id = 1;
UPDATE trait_text SET name = 'Attributsanpassung (+2 IN, +2 CH)' WHERE trait_id = 53 AND language_id = 1;
UPDATE trait_text SET name = 'Zauberresistenz' WHERE trait_id = 54 AND language_id = 1;
UPDATE trait_text SET name = 'Zauberbonus (Dunkelelf)' WHERE trait_id = 55 AND language_id = 1;
UPDATE trait_text SET name = 'Umgang mit Waffen (Schwert und Armbrust)' WHERE trait_id = 56 AND language_id = 1;
UPDATE trait_text SET name = 'Blindheit durch Licht' WHERE trait_id = 57 AND language_id = 1;
UPDATE trait_text SET name = 'Attributsanpassung (+2 IN, -2 ST)' WHERE trait_id = 58 AND language_id = 1;
UPDATE trait_text SET name = 'Attributsanpassung (+2 GE, -2 IN)' WHERE trait_id = 59 AND language_id = 1;
UPDATE trait_text SET name = 'Attributsanpassung (+2 ST, -2 IN)' WHERE trait_id = 60 AND language_id = 1;
UPDATE trait_text SET name = 'Attributsanpassung (-2 ST, +2 GE, +2 WE, -4 CH)' WHERE trait_id = 61 AND language_id = 1;
UPDATE trait_text SET name = 'Unglueck Widerstehen' WHERE trait_id = 62 AND language_id = 1;
UPDATE trait_text SET name = 'Zauberbonus (Tiefengnom)' WHERE trait_id = 63 AND language_id = 1;
UPDATE trait_text SET name = 'Zauberbonus (Unauffindbarkeit)' WHERE trait_id = 64 AND language_id = 1;
UPDATE trait_text SET name = 'Fertigkeitsbonus (Verstecken)' WHERE trait_id = 65 AND language_id = 1;
UPDATE trait_text SET name = 'Zauberbonus (Waldgnom)' WHERE trait_id = 66 AND language_id = 1;
UPDATE trait_text SET name = 'Feindseligkeit (Kobolde, Goblinoiden, Orks und Reptilien)' WHERE trait_id = 67 AND language_id = 1;
UPDATE trait_text SET name = 'Fertigkeitsbonus, maechtiger (Verstecken)' WHERE trait_id = 68 AND language_id = 1;
UPDATE trait_text SET name = 'Fertigkeitsbonus (Suchen, Entdecken, Lauschen)' WHERE trait_id = 69 AND language_id = 1;

UPDATE race_text SET name = 'Hill Dwarf' WHERE name = 'Hill dwarf';
UPDATE race_text SET name = 'Deep Dwarf' WHERE name = 'Deep dwarf';
UPDATE race_text SET name = 'Mountain Dwarf' WHERE name = 'Mountain dwarf';
