ALTER TABLE weapon_text ADD description VARCHAR(150);
ALTER TABLE armor_text ADD description VARCHAR(150);
ALTER TABLE good_text ADD description VARCHAR(150);

UPDATE weapon_text SET description = 'Player''s Handbook page 117' WHERE weapon_id = 0 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 116' WHERE weapon_id = 1 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 116' WHERE weapon_id = 2 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 118' WHERE weapon_id = 3 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 119' WHERE weapon_id = 4 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 121' WHERE weapon_id = 5 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 115' WHERE weapon_id = 6 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 119' WHERE weapon_id = 7 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 119' WHERE weapon_id = 8 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 121' WHERE weapon_id = 9 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 119' WHERE weapon_id = 10 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 120' WHERE weapon_id = 11 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 121' WHERE weapon_id = 12 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 115' WHERE weapon_id = 13 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 115' WHERE weapon_id = 14 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 116' WHERE weapon_id = 15 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 118' WHERE weapon_id = 16 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 121' WHERE weapon_id = 17 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 114' WHERE weapon_id = 18 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 118' WHERE weapon_id = 19 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 118' WHERE weapon_id = 20 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 118' WHERE weapon_id = 21 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 120' WHERE weapon_id = 22 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 120' WHERE weapon_id = 23 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 121' WHERE weapon_id = 24 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 115' WHERE weapon_id = 25 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 117' WHERE weapon_id = 26 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 119' WHERE weapon_id = 27 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 120' WHERE weapon_id = 28 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 120' WHERE weapon_id = 29 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 120' WHERE weapon_id = 30 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 121' WHERE weapon_id = 31 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 121' WHERE weapon_id = 32 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 117' WHERE weapon_id = 33 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 118' WHERE weapon_id = 34 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 118' WHERE weapon_id = 35 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 118' WHERE weapon_id = 36 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 117' WHERE weapon_id = 37 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 118' WHERE weapon_id = 38 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 118' WHERE weapon_id = 39 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 118' WHERE weapon_id = 40 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 118' WHERE weapon_id = 41 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 120' WHERE weapon_id = 42 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 120' WHERE weapon_id = 43 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 118' WHERE weapon_id = 44 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 119' WHERE weapon_id = 45 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 120' WHERE weapon_id = 46 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 120' WHERE weapon_id = 47 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 118' WHERE weapon_id = 48 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 120' WHERE weapon_id = 49 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 120' WHERE weapon_id = 50 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 121' WHERE weapon_id = 51 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 121' WHERE weapon_id = 52 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 121' WHERE weapon_id = 53 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 121' WHERE weapon_id = 54 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 115' WHERE weapon_id = 55 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 115' WHERE weapon_id = 56 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 117' WHERE weapon_id = 57 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 118' WHERE weapon_id = 58 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 121' WHERE weapon_id = 59 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 121' WHERE weapon_id = 60 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 115' WHERE weapon_id = 61 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 115' WHERE weapon_id = 62 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 116' WHERE weapon_id = 63 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 116' WHERE weapon_id = 64 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 121' WHERE weapon_id = 65 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 115' WHERE weapon_id = 66 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 115' WHERE weapon_id = 67 AND language_id = 0;
UPDATE weapon_text SET description = 'Player''s Handbook page 114' WHERE weapon_id = 68 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 226' WHERE weapon_id = 69 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 226' WHERE weapon_id = 70 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 226' WHERE weapon_id = 71 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 226' WHERE weapon_id = 72 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 226' WHERE weapon_id = 73 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 226' WHERE weapon_id = 74 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 226' WHERE weapon_id = 75 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 226' WHERE weapon_id = 76 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 226' WHERE weapon_id = 77 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 227' WHERE weapon_id = 78 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 227' WHERE weapon_id = 79 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 227' WHERE weapon_id = 80 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 227' WHERE weapon_id = 81 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 227' WHERE weapon_id = 82 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 227' WHERE weapon_id = 83 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 227' WHERE weapon_id = 84 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 227' WHERE weapon_id = 85 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 227' WHERE weapon_id = 86 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 227' WHERE weapon_id = 87 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 227' WHERE weapon_id = 88 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 227' WHERE weapon_id = 89 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 228' WHERE weapon_id = 90 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 228' WHERE weapon_id = 91 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 228' WHERE weapon_id = 92 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 228' WHERE weapon_id = 93 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 228' WHERE weapon_id = 94 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 228' WHERE weapon_id = 95 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 228' WHERE weapon_id = 96 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 228' WHERE weapon_id = 97 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 228' WHERE weapon_id = 98 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 228' WHERE weapon_id = 99 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 229' WHERE weapon_id = 100 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 229' WHERE weapon_id = 101 AND language_id = 0;
UPDATE weapon_text SET description = 'Dungeon Master''s Guide page 229' WHERE weapon_id = 102 AND language_id = 0;



UPDATE weapon_text SET description = 'Spieler Handbuch Seite 145' WHERE weapon_id = 0 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 141' WHERE weapon_id = 1 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 2 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 3 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 145' WHERE weapon_id = 4 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 5 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 142' WHERE weapon_id = 6 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 145' WHERE weapon_id = 7 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 145' WHERE weapon_id = 8 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 144' WHERE weapon_id = 9 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 144' WHERE weapon_id = 10 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 142' WHERE weapon_id = 11 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 12 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 13 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 144' WHERE weapon_id = 14 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 147' WHERE weapon_id = 15 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 147' WHERE weapon_id = 16 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 17 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 147' WHERE weapon_id = 18 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 145' WHERE weapon_id = 19 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 141' WHERE weapon_id = 20 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 144' WHERE weapon_id = 21 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 145' WHERE weapon_id = 22 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 23 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 144' WHERE weapon_id = 24 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 25 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 26 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 144' WHERE weapon_id = 27 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 145' WHERE weapon_id = 28 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 145' WHERE weapon_id = 29 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 144' WHERE weapon_id = 30 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 141' WHERE weapon_id = 31 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 32 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 144' WHERE weapon_id = 33 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 141' WHERE weapon_id = 34 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 147' WHERE weapon_id = 35 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 147' WHERE weapon_id = 36 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 37 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 147' WHERE weapon_id = 38 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 142' WHERE weapon_id = 39 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 142' WHERE weapon_id = 40 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 144' WHERE weapon_id = 41 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 145' WHERE weapon_id = 42 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 43 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 144' WHERE weapon_id = 44 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 143' WHERE weapon_id = 45 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 144' WHERE weapon_id = 46 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 142' WHERE weapon_id = 47 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 142' WHERE weapon_id = 48 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 145' WHERE weapon_id = 49 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 50 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 51 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 141' WHERE weapon_id = 52 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 147' WHERE weapon_id = 53 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 145' WHERE weapon_id = 54 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 145' WHERE weapon_id = 55 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 56 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 57 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 141' WHERE weapon_id = 58 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 141' WHERE weapon_id = 59 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 147' WHERE weapon_id = 60 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 141' WHERE weapon_id = 61 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 142' WHERE weapon_id = 62 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 145' WHERE weapon_id = 63 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 145' WHERE weapon_id = 64 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 65 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 139' WHERE weapon_id = 66 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 146' WHERE weapon_id = 67 AND language_id = 1;
UPDATE weapon_text SET description = 'Spieler Handbuch Seite 145' WHERE weapon_id = 68 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 281' WHERE weapon_id = 69 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 281' WHERE weapon_id = 70 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 281' WHERE weapon_id = 71 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 281' WHERE weapon_id = 72 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 284' WHERE weapon_id = 73 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 281' WHERE weapon_id = 74 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 281' WHERE weapon_id = 75 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 281' WHERE weapon_id = 76 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 281' WHERE weapon_id = 77 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 282' WHERE weapon_id = 78 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 281' WHERE weapon_id = 79 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 281' WHERE weapon_id = 80 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 281' WHERE weapon_id = 81 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 281' WHERE weapon_id = 82 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 283' WHERE weapon_id = 83 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 283' WHERE weapon_id = 84 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 282' WHERE weapon_id = 85 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 282' WHERE weapon_id = 86 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 283' WHERE weapon_id = 87 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 281' WHERE weapon_id = 88 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 282' WHERE weapon_id = 89 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 282' WHERE weapon_id = 90 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 282' WHERE weapon_id = 91 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 283' WHERE weapon_id = 92 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 283' WHERE weapon_id = 93 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 283' WHERE weapon_id = 94 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 282' WHERE weapon_id = 95 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 283' WHERE weapon_id = 96 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 284' WHERE weapon_id = 97 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 282' WHERE weapon_id = 98 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 282' WHERE weapon_id = 99 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 282' WHERE weapon_id = 100 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 281' WHERE weapon_id = 101 AND language_id = 1;
UPDATE weapon_text SET description = 'Spielleiter Handbuch Seite 281' WHERE weapon_id = 102 AND language_id = 1;
