CREATE TABLE combat_type
(id       INTEGER,
 name     VARCHAR(16) NOT NULL,
 PRIMARY KEY (id)
);
INSERT INTO combat_type VALUES (0, 'Melee Weapon');
INSERT INTO combat_type VALUES (1, 'Ranged Weapon');


CREATE TABLE weapon_encumbrance
(id       INTEGER,
 name     VARCHAR(32) NOT NULL,
 PRIMARY KEY (id)
);
INSERT INTO weapon_encumbrance VALUES (0, 'Light Melee Weapon');
INSERT INTO weapon_encumbrance VALUES (1, 'One-Handed Melee Weapon');
INSERT INTO weapon_encumbrance VALUES (2, 'Two-Handed Melee Weapon');
INSERT INTO weapon_encumbrance VALUES (3, 'Light Ranged Weapon');
INSERT INTO weapon_encumbrance VALUES (4, 'One-Handed Ranged Weapon');
INSERT INTO weapon_encumbrance VALUES (5, 'Two-Handed Ranged Weapon');


CREATE TABLE weapon_category
(id       INTEGER,
 name     VARCHAR(32) NOT NULL,
 PRIMARY KEY (id)
);
INSERT INTO weapon_category VALUES (0, 'Normal Weapon');
INSERT INTO weapon_category VALUES (1, 'Reach Weapon');
INSERT INTO weapon_category VALUES (2, 'Double Weapon');
INSERT INTO weapon_category VALUES (3, 'Thrown Weapon');
INSERT INTO weapon_category VALUES (4, 'Projectile Weapon');
INSERT INTO weapon_category VALUES (5, 'Ammunition');


CREATE TABLE weapon_family
(id       INTEGER,
 name     VARCHAR(32) NOT NULL,
 PRIMARY KEY (id)
);
INSERT INTO weapon_family VALUES (1, 'Unarmed strike' );
INSERT INTO weapon_family VALUES (2, 'Dagger' );
INSERT INTO weapon_family VALUES (3, 'Mace, light' );
INSERT INTO weapon_family VALUES (4, 'Sickle' );
INSERT INTO weapon_family VALUES (5, 'Club' );
INSERT INTO weapon_family VALUES (6, 'Mace, heavy' );
INSERT INTO weapon_family VALUES (7, 'Morningstar' );
INSERT INTO weapon_family VALUES (8, 'Shortspear' );
INSERT INTO weapon_family VALUES (9, 'Longspear' );
INSERT INTO weapon_family VALUES (10, 'Quarterstaff' );
INSERT INTO weapon_family VALUES (11, 'Spear' );
INSERT INTO weapon_family VALUES (12, 'Crossbow, heavy' );
INSERT INTO weapon_family VALUES (13, 'Crossbow, light' );
INSERT INTO weapon_family VALUES (14, 'Dart' );
INSERT INTO weapon_family VALUES (15, 'Javelin' );
INSERT INTO weapon_family VALUES (16, 'Sling' );
INSERT INTO weapon_family VALUES (17, 'Axe, throwing' );
INSERT INTO weapon_family VALUES (18, 'Hammer, light' );
INSERT INTO weapon_family VALUES (19, 'Handaxe' );
INSERT INTO weapon_family VALUES (20, 'Kukri' );
INSERT INTO weapon_family VALUES (21, 'Pick, light' );
INSERT INTO weapon_family VALUES (22, 'Sap' );
INSERT INTO weapon_family VALUES (23, 'Shield, light' );
INSERT INTO weapon_family VALUES (24, 'Spiked armor' );
INSERT INTO weapon_family VALUES (25, 'Sword, short' );
INSERT INTO weapon_family VALUES (26, 'Battleaxe' );
INSERT INTO weapon_family VALUES (27, 'Flail' );
INSERT INTO weapon_family VALUES (28, 'Longsword' );
INSERT INTO weapon_family VALUES (29, 'Pick, heavy' );
INSERT INTO weapon_family VALUES (30, 'Rapier' );
INSERT INTO weapon_family VALUES (31, 'Scimitar' );
INSERT INTO weapon_family VALUES (32, 'Shield, heavy' );
INSERT INTO weapon_family VALUES (33, 'Trident' );
INSERT INTO weapon_family VALUES (34, 'Warhammer' );
INSERT INTO weapon_family VALUES (35, 'Falchion' );
INSERT INTO weapon_family VALUES (36, 'Glaive' );
INSERT INTO weapon_family VALUES (37, 'Greataxe' );
INSERT INTO weapon_family VALUES (38, 'Greatclub' );
INSERT INTO weapon_family VALUES (39, 'Flail, heavy' );
INSERT INTO weapon_family VALUES (40, 'Greatsword' );
INSERT INTO weapon_family VALUES (41, 'Guisarme' );
INSERT INTO weapon_family VALUES (42, 'Halberd' );
INSERT INTO weapon_family VALUES (43, 'Lance' );
INSERT INTO weapon_family VALUES (44, 'Ranseur' );
INSERT INTO weapon_family VALUES (45, 'Scythe' );
INSERT INTO weapon_family VALUES (46, 'Longbow' );
INSERT INTO weapon_family VALUES (47, 'Longbow, composite' );
INSERT INTO weapon_family VALUES (48, 'Shortbow' );
INSERT INTO weapon_family VALUES (49, 'Shortbow, composite' );
INSERT INTO weapon_family VALUES (50, 'Kama' );
INSERT INTO weapon_family VALUES (51, 'Nunchaku' );
INSERT INTO weapon_family VALUES (52, 'Sai' );
INSERT INTO weapon_family VALUES (53, 'Siangham' );
INSERT INTO weapon_family VALUES (54, 'Sword, bastard' );
INSERT INTO weapon_family VALUES (55, 'Waraxe, dwarven' );
INSERT INTO weapon_family VALUES (56, 'Whip' );
INSERT INTO weapon_family VALUES (57, 'Axe, orc double' );
INSERT INTO weapon_family VALUES (58, 'Chain, spiked' );
INSERT INTO weapon_family VALUES (59, 'Flail, dire' );
INSERT INTO weapon_family VALUES (60, 'Hammer, gnome hooked' );
INSERT INTO weapon_family VALUES (61, 'Sword, two-bladed' );
INSERT INTO weapon_family VALUES (62, 'Urgrosh, dwarven' );
INSERT INTO weapon_family VALUES (63, 'Bolas' );
INSERT INTO weapon_family VALUES (64, 'Crossbow, hand' );
INSERT INTO weapon_family VALUES (65, 'Crossbow, repeating heavy' );
INSERT INTO weapon_family VALUES (66, 'Crossbow, repeating light' );
INSERT INTO weapon_family VALUES (67, 'Net' );
INSERT INTO weapon_family VALUES (68, 'Shuriken' );
INSERT INTO weapon_family VALUES (69, 'Ammunition' );
INSERT INTO weapon_family VALUES (70, 'Grapple' );
INSERT INTO weapon_family VALUES (71, 'Ray' );


CREATE TABLE attack_wield
(id       INTEGER,
 name     VARCHAR(32) NOT NULL,
 PRIMARY KEY (id)
);
INSERT INTO attack_wield VALUES (0, 'Normal Weapon' );
INSERT INTO attack_wield VALUES (1, 'Reach  Weapon' );
INSERT INTO attack_wield VALUES (2, 'Double Weapon' );
INSERT INTO attack_wield VALUES (3, 'Thrown Weapon' );
INSERT INTO attack_wield VALUES (4, 'Projectile Weapon' );
INSERT INTO attack_wield VALUES (5, 'Ammunition' );


CREATE TABLE weapon_attack
(id                INTEGER,
 charakter_id      INTEGER,
 name              VARCHAR(32),
 description       VARCHAR(2048),
 attack_wield_id   INTEGER DEFAULT 0,
 weapon_id         INTEGER DEFAULT 0,
 ammunition        INTEGER DEFAULT 0,
 PRIMARY KEY (id),
 FOREIGN KEY (charakter_id) REFERENCES charakter(id),
 FOREIGN KEY (attack_wield_id) REFERENCES attack_wield(id),
 FOREIGN KEY (weapon_id) REFERENCES weapon(id)
);


CREATE TABLE weapon_temp
(id                      INTEGER,
 name                    VARCHAR(30),
 description             VARCHAR(2048),
 cost                    FLOAT DEFAULT 0,
 weight                  FLOAT DEFAULT 0,
 number_of_dice          INTEGER DEFAULT 0,
 die_id                  INTEGER DEFAULT 0,
 enhancement_bonus       INTEGER DEFAULT 0,
 critical_hit            INTEGER DEFAULT 0,
 critical_mod            INTEGER DEFAULT 0,
 weapon_type_id          INTEGER DEFAULT 0,
 quality_type_id         INTEGER DEFAULT 0,
 combat_type_id          INTEGER DEFAULT 0,
 weapon_encumbrance_id   INTEGER DEFAULT 0,
 weapon_category_id      INTEGER DEFAULT 0,
 weapon_family_id        INTEGER DEFAULT 1,
 range_increment         INTEGER DEFAULT 0,
 PRIMARY KEY (id),
 FOREIGN KEY (die_id) REFERENCES die(id),
 FOREIGN KEY (weapon_type_id) REFERENCES weapon_type(id)
 FOREIGN KEY (quality_type_id) REFERENCES quality_type(id)
 FOREIGN KEY (combat_type_id) REFERENCES combat_type(id)
 FOREIGN KEY (weapon_encumbrance_id) REFERENCES weapon_encumbrance(id)
 FOREIGN KEY (weapon_category_id) REFERENCES weapon_category(id)
 FOREIGN KEY (weapon_family_id) REFERENCES weapon_family(id)
);

INSERT INTO weapon_temp (id, name, description, cost, weight, number_of_dice, die_id, enhancement_bonus, critical_hit, critical_mod, weapon_type_id, quality_type_id) SELECT id, name, description, cost, weight, number_of_dice, die_id, bonus, critical_hit, critical_mod, weapon_type_id, quality_type_id FROM weapon WHERE id > 102;
UPDATE weapon_temp SET id = id + 7;
DROP TABLE weapon;
ALTER TABLE weapon_temp RENAME TO weapon;
UPDATE charakter_weapon SET weapon_id = weapon_id + 7 WHERE weapon_id > 102;

INSERT INTO weapon VALUES ( 0, 'Gauntlet', 'This metal glove lets you deal lethal damage rather than nonlethal damage with unarmed strikes. A strike with a gauntlet is otherwise considered an unarmed attack. The cost and weight given are for a single gauntlet. Medium and heavy armors (except breastplate) come with gauntlets.', 2, 1, 1, 1, 0, 20, 2, 0, 0, 0, 0, 0, 1, 0 );
INSERT INTO weapon VALUES ( 1, 'Dagger', 'You get a +2 bonus on Sleight of Hand checks made to conceal a dagger on your body (see the Sleight of Hand skill)', 2, 1, 1, 2, 0, 19, 2, 0, 0, 0, 0, 0, 2, 10 );
INSERT INTO weapon VALUES ( 2, 'Dagger, punching', '', 2, 1, 1, 2, 0, 20, 3, 0, 0, 0, 0, 0, 2, 0 );
INSERT INTO weapon VALUES ( 3, 'Gauntlet, spiked', 'Your opponent cannot use a disarm action to disarm you of spiked gauntlets. The cost and weight given are for a single gauntlet. An attack with a spiked gauntlet is considered an armed attack.', 5, 1, 1, 2, 0, 20, 2, 0, 0, 0, 0, 0, 1, 0 );
INSERT INTO weapon VALUES ( 4, 'Mace, light', '', 5, 4, 1, 3, 0, 20, 2, 0, 0, 0, 0, 0, 3, 0 );
INSERT INTO weapon VALUES ( 5, 'Sickle', 'A sickle can be used to make trip attacks. If you are tripped during your own trip attempt, you can drop the sickle to avoid being tripped.', 6, 2, 1, 3, 0, 20, 2, 0, 0, 0, 0, 0, 4, 0 );
INSERT INTO weapon VALUES ( 6, 'Club', '', 0, 3, 1, 3, 0, 20, 2, 0, 0, 0, 1, 0, 5, 10 );
INSERT INTO weapon VALUES ( 7, 'Mace, heavy', '', 12, 8, 1, 4, 0, 20, 2, 0, 0, 0, 1, 0, 6, 0 );
INSERT INTO weapon VALUES ( 8, 'Morningstar', '', 8, 6, 1, 4, 0, 20, 2, 0, 0, 0, 1, 0, 7, 0 );
INSERT INTO weapon VALUES ( 9, 'Shortspear', 'A shortspear is small enough to wield one-handed. It may also be thrown.', 1, 3, 1, 3, 0, 20, 2, 0, 0, 0, 1, 0, 8, 20 );
INSERT INTO weapon VALUES ( 10, 'Longspear', 'A longspear has reach. You can strike opponents 10 feet away with it, but you can''t use it against an adjacent foe. If you use a ready action to set a longspear against a charge, you deal double damage on a successful hit against a charging character.', 5, 9, 1, 4, 0, 20, 3, 0, 0, 0, 2, 1, 9, 0 );
INSERT INTO weapon VALUES ( 11, 'Quarterstaff', 'A quarterstaff is a double weapon. You can fight with it as if fighting with two weapons, but if you do, you incur all the normal attack penalties associated with fighting with two weapons, just as if you were using a one-handed weapon and a light weapon. A creature wielding a quarterstaff in one hand can''t use it as a double weapon - only one end of the weapon can be used in any given round.\nThe quarterstaff is a special monk weapon. This designation gives a monk wielding a quarterstaff special options.\n', 0, 4, 1, 3, 0, 20, 2, 0, 0, 0, 2, 2, 10, 0 );
INSERT INTO weapon VALUES ( 12, 'Spear', 'A spear can be thrown. If you use a ready action to set a spear against a charge, you deal double damage on a successful hit against a charging character.', 2, 6, 1, 4, 0, 20, 3, 0, 0, 0, 2, 0, 11, 20 );
INSERT INTO weapon VALUES ( 13, 'Crossbow, heavy', 'You draw a heavy crossbow back by turning a small winch. Loading a heavy crossbow is a full-round action that provokes attacks of opportunity.\nNormally, operating a heavy crossbow requires two hands. However, you can shoot, but not load, a heavy crossbow with one hand at a -4 penalty on attack rolls. You can shoot a heavy crossbow with each hand, but you take a penalty on attack rolls as if attacking with two one-handed weapons. This penalty is cumulative with the penalty for one-handed firing.', 50, 8, 1, 5, 0, 19, 2, 0, 0, 1, 4, 4, 12, 120 );
INSERT INTO weapon VALUES ( 14, 'Crossbow, light', 'You draw a light crossbow back by pulling a lever. Loading a light crossbow is a move action that provokes attacks of opportunity.\nNormally, operating a light crossbow requires two hands. However, you can shoot, but not load, a light crossbow with one hand at a -2 penalty on attack rolls. You can shoot a light crossbow with each hand, but you take a penalty on attack rolls as if attacking with two light weapons. This penalty is cumulative with the penalty for one-handed firing.', 35, 4, 1, 4, 0, 19, 2, 0, 0, 1, 4, 4, 13, 80 );
INSERT INTO weapon VALUES ( 15, 'Dart', '', 5, 0.5, 1, 2, 0, 20, 2, 0, 0, 1, 3, 3, 14, 20 );
INSERT INTO weapon VALUES ( 16, 'Javelin', 'Since it is not designed for melee, you are treated as nonproficient with it and take a -4 penalty on attack rolls if you use a javelin as a melee weapon.', 1, 2, 1, 3, 0, 20, 2, 0, 0, 1, 4, 3, 15, 30 );
INSERT INTO weapon VALUES ( 17, 'Sling', 'Your Strength modifier applies to damage rolls when you use a sling, just as it does for thrown weapons. You can fire, but not load, a sling with one hand. Loading a sling is a move action that requires two hands and provokes attacks of opportunity.\nYou can hurl ordinary stones with a sling, but stones are not as dense or as round as bullets. Thus, such an attack deals damage as if the weapon were designed for a creature one size category smaller than you and you take a -1 penalty on attack rolls.\n', 0, 0.1, 1, 2, 0, 20, 2, 0, 0, 1, 4, 4, 16, 50 );
INSERT INTO weapon VALUES ( 18, 'Axe, throwing', '', 8, 2, 1, 3, 0, 20, 2, 1, 0, 0, 0, 3, 17, 10 );
INSERT INTO weapon VALUES ( 19, 'Hammer, light', '', 1, 2, 1, 2, 0, 20, 2, 1, 0, 0, 0, 3, 18, 20 );
INSERT INTO weapon VALUES ( 20, 'Handaxe', '', 6, 3, 1, 3, 0, 20, 3, 1, 0, 0, 0, 0, 19, 0 );
INSERT INTO weapon VALUES ( 21, 'Kukri', '', 8, 2, 1, 2, 0, 18, 2, 1, 0, 0, 0, 0, 20, 0 );
INSERT INTO weapon VALUES ( 22, 'Pick, light', '', 4, 3, 1, 2, 0, 20, 4, 1, 0, 0, 0, 0, 21, 0 );
INSERT INTO weapon VALUES ( 23, 'Sap', '', 1, 2, 1, 3, 0, 20, 2, 1, 0, 0, 0, 0, 22, 0 );
INSERT INTO weapon VALUES ( 24, 'Sword, short', '', 10, 2, 1, 3, 0, 19, 2, 1, 0, 0, 0, 0, 25, 0 );
INSERT INTO weapon VALUES ( 25, 'Battleaxe', '', 10, 6, 1, 4, 0, 20, 3, 1, 0, 0, 1, 0, 26, 0 );
INSERT INTO weapon VALUES ( 26, 'Flail', 'With a flail, you get a +2 bonus on opposed attack rolls made to disarm an enemy (including the roll to avoid being disarmed if such an attempt fails).\nYou can also use this weapon to make trip attacks. If you are tripped during your own trip attempt, you can drop the flail to avoid being tripped.\n', 8, 5, 1, 4, 0, 20, 2, 1, 0, 0, 1, 0, 27, 0 );
INSERT INTO weapon VALUES ( 27, 'Longsword', '', 15, 4, 1, 4, 0, 19, 2, 1, 0, 0, 1, 0, 28, 0 );
INSERT INTO weapon VALUES ( 28, 'Pick, heavy', '', 8, 6, 1, 3, 0, 20, 4, 1, 0, 0, 1, 0, 29, 0 );
INSERT INTO weapon VALUES ( 29, 'Rapier', 'You can use the Weapon Finesse feat to apply your Dexterity modifier instead of your Strength modifier to attack rolls with a rapier sized for you, even though it isn''t a light weapon for you. You can''t wield a rapier in two hands in order to apply 1-1/2 times your Strength bonus to damage.', 20, 2, 1, 3, 0, 18, 2, 1, 0, 0, 1, 0, 30, 0 );
INSERT INTO weapon VALUES ( 30, 'Scimitar', '', 15, 4, 1, 3, 0, 18, 2, 1, 0, 0, 1, 0, 31, 0 );
INSERT INTO weapon VALUES ( 31, 'Trident', 'This weapon can be thrown. If you use a ready action to set a trident against a charge, you deal double damage on a successful hit against a charging character.', 15, 4, 1, 4, 0, 20, 2, 1, 0, 0, 1, 0, 33, 10 );
INSERT INTO weapon VALUES ( 32, 'Warhammer', '', 12, 5, 1, 4, 0, 20, 3, 1, 0, 0, 1, 0, 34, 0 );
INSERT INTO weapon VALUES ( 33, 'Falchion', '', 75, 8, 2, 2, 0, 18, 2, 1, 0, 0, 2, 0, 35, 0 );
INSERT INTO weapon VALUES ( 34, 'Glaive', 'A glaive has reach. You can strike opponents 10 feet away with it, but you can''t use it against an adjacent foe.', 8, 10, 1, 5, 0, 20, 3, 1, 0, 0, 2, 1, 36, 0 );
INSERT INTO weapon VALUES ( 35, 'Greataxe', '', 20, 12, 1, 6, 0, 20, 3, 1, 0, 0, 2, 0, 37, 0 );
INSERT INTO weapon VALUES ( 36, 'Greatclub', '', 5, 8, 1, 5, 0, 20, 2, 1, 0, 0, 2, 0, 38, 0 );
INSERT INTO weapon VALUES ( 37, 'Flail, heavy', 'With a flail, you get a +2 bonus on opposed attack rolls made to disarm an enemy (including the roll to avoid being disarmed if such an attempt fails).\nYou can also use this weapon to make trip attacks. If you are tripped during your own trip attempt, you can drop the flail to avoid being tripped.\n', 15, 10, 1, 5, 0, 19, 2, 1, 0, 0, 2, 0, 39, 0 );
INSERT INTO weapon VALUES ( 38, 'Greatsword', '', 50, 8, 2, 3, 0, 19, 2, 1, 0, 0, 2, 0, 40, 0 );
INSERT INTO weapon VALUES ( 39, 'Guisarme', 'A guisarme has reach. You can strike opponents 10 feet away with it, but you can''t use it against an adjacent foe.\nYou can also use it to make trip attacks. If you are tripped during your own trip attempt, you can drop the guisarme to avoid being tripped.\n', 9, 12, 2, 2, 0, 20, 3, 1, 0, 0, 2, 1, 41, 0 );
INSERT INTO weapon VALUES ( 40, 'Halberd', 'If you use a ready action to set a halberd against a charge, you deal double damage on a successful hit against a charging character.\nYou can use a halberd to make trip attacks. If you are tripped during your own trip attempt, you can drop the halberd to avoid being tripped.\n', 10, 12, 1, 5, 0, 20, 3, 1, 0, 0, 2, 0, 42, 0 );
INSERT INTO weapon VALUES ( 41, 'Lance', 'A lance deals double damage when used from the back of a charging mount. It has reach, so you can strike opponents 10 feet away with it, but you can''t use it against an adjacent foe.\nWhile mounted, you can wield a lance with one hand.\n', 10, 10, 1, 4, 0, 20, 3, 1, 0, 0, 2, 1, 43, 0 );
INSERT INTO weapon VALUES ( 42, 'Ranseur', 'A ranseur has reach. You can strike opponents 10 feet away with it, but you can''t use it against an adjacent foe.\nWith a ranseur, you get a +2 bonus on opposed attack rolls made to disarm an opponent (including the roll to avoid being disarmed if such an attempt fails).\n', 10, 12, 2, 2, 0, 20, 3, 1, 0, 0, 2, 1, 44, 0 );
INSERT INTO weapon VALUES ( 43, 'Scythe', 'A scythe can be used to make trip attacks. If you are tripped during your own trip attempt, you can drop the scythe to avoid being tripped.', 18, 10, 2, 2, 0, 20, 4, 1, 0, 0, 2, 0, 45, 0 );
INSERT INTO weapon VALUES ( 44, 'Longbow', 'You need at least two hands to use a bow, regardless of its size. A longbow is too unwieldy to use while you are mounted. If you have a penalty for low Strength, apply it to damage rolls when you use a longbow. If you have a bonus for high Strength, you can apply it to damage rolls when you use a composite longbow (see below) but not a regular longbow.', 75, 3, 1, 4, 0, 20, 3, 1, 0, 1, 5, 4, 46, 100 );
INSERT INTO weapon VALUES ( 45, 'Longbow, composite', 'You need at least two hands to use a bow, regardless of its size. You can use a composite longbow while mounted. All composite bows are made with a particular strength rating (that is, each requires a minimum Strength modifier to use with proficiency). If your Strength bonus is less than the strength rating of the composite bow, you can''t effectively use it, so you take a -2 penalty on attacks with it. The default composite longbow requires a Strength modifier of +0 or higher to use with proficiency. A composite longbow can be made with a high strength rating to take advantage of an above-average Strength score, this feature allows you to add your Strength bonus to damage, up to the maximum bonus indicated for the bow. Each point of Strength bonus granted by the bow adds 100 gp to its cost.\nFor purposes of weapon proficiency and similar feats, a composite longbow is treated as if it were a longbow.\n', 100, 3, 1, 4, 0, 20, 3, 1, 0, 1, 5, 4, 47, 110 );
INSERT INTO weapon VALUES ( 46, 'Shortbow', 'You need at least two hands to use a bow, regardless of its size. You can use a shortbow while mounted. If you have a penalty for low Strength, apply it to damage rolls when you use a shortbow. If you have a bonus for high Strength, you can apply it to damage rolls when you use a composite shortbow (see below) but not a regular shortbow.', 30, 2, 1, 3, 0, 20, 3, 1, 0, 1, 5, 4, 48, 60 );
INSERT INTO weapon VALUES ( 47, 'Shortbow, composite', 'You need at least two hands to use a bow, regardless of its size. You can use a composite shortbow while mounted. All composite bows are made with a particular strength rating (that is, each requires a minimum Strength modifier to use with proficiency). If your Strength bonus is lower than the strength rating of the composite bow, you can''t effectively use it, so you take a -2 penalty on attacks with it. The default composite shortbow requires a Strength modifier of +0 or higher to use with proficiency. A composite shortbow can be made with a high strength rating to take advantage of an above-average Strength score, this feature allows you to add your Strength bonus to damage, up to the maximum bonus indicated for the bow. Each point of Strength bonus granted by the bow adds 75 gp to its cost. \nFor purposes of weapon proficiency and similar feats, a composite shortbow is treated as if it were a shortbow.\n', 75, 2, 1, 3, 0, 20, 3, 1, 0, 1, 5, 4, 49, 70 );
INSERT INTO weapon VALUES ( 48, 'Kama', 'The kama is a special monk weapon. This designation gives a monk wielding a kama special options.\nYou can use a kama to make trip attacks. If you are tripped during your own trip attempt, you can drop the kama to avoid being tripped.\n', 2, 2, 1, 3, 0, 20, 2, 2, 0, 0, 0, 0, 50, 0 );
INSERT INTO weapon VALUES ( 49, 'Nunchaku', 'The nunchaku is a special monk weapon. This designation gives a monk wielding a nunchaku special options. With a nunchaku, you get a +2 bonus on opposed attack rolls made to disarm an enemy (including the roll to avoid being disarmed if such an attempt fails).', 2, 2, 1, 3, 0, 20, 2, 2, 0, 0, 0, 0, 51, 0 );
INSERT INTO weapon VALUES ( 50, 'Sai', 'You can use the Weapon Finesse feat to apply your Dexterity modifier instead of your Strength modifier to attack rolls with a rapier sized for you, even though it isn''t a light weapon for you. You can''t wield a rapier in two hands in order to apply 1-1/2 times your Strength bonus to damage.With a sai, you get a +4 bonus on opposed attack rolls made to disarm an enemy (including the roll to avoid being disarmed if such an attempt fails).\nThe sai is a special monk weapon. This designation gives a monk wielding a sai special options.\n', 1, 1, 1, 2, 0, 20, 2, 2, 0, 0, 0, 0, 52, 10 );
INSERT INTO weapon VALUES ( 51, 'Siangham', 'The siangham is a special monk weapon. This designation gives a monk wielding a siangham special options.', 3, 1, 1, 3, 0, 20, 2, 2, 0, 0, 0, 0, 53, 0 );
INSERT INTO weapon VALUES ( 52, 'Sword, bastard', 'A bastard sword is too large to use in one hand without special training, thus, it is an exotic weapon. A character can use a bastard sword two-handed as a martial weapon.', 35, 6, 1, 5, 0, 19, 2, 2, 0, 0, 1, 0, 54, 0 );
INSERT INTO weapon VALUES ( 53, 'Waraxe, dwarven', 'A dwarven waraxe is too large to use in one hand without special training, thus, it is an exotic weapon. A Medium character can use a dwarven waraxe two-handed as a martial weapon, or a Large creature can use it one-handed in the same way. A dwarf treats a dwarven waraxe as a martial weapon even when using it in one hand.', 30, 8, 1, 5, 0, 20, 3, 2, 0, 0, 1, 0, 55, 0 );
INSERT INTO weapon VALUES ( 54, 'Whip', 'A whip deals nonlethal damage. It deals no damage to any creature with an armor bonus of +1 or higher or a natural armor bonus of +3 or higher. The whip is treated as a melee weapon with 15-foot reach, though you don''t threaten the area into which you can make an attack. In addition, unlike most other weapons with reach, you can use it against foes anywhere within your reach (including adjacent foes).\nUsing a whip provokes an attack of opportunity, just as if you had used a ranged weapon.\nYou can make trip attacks with a whip. If you are tripped during your own trip attempt, you can drop the whip to avoid being tripped.\nWhen using a whip, you get a +2 bonus on opposed attack rolls made to disarm an opponent (including the roll to keep from being disarmed if the attack fails).\nYou can use the Weapon Finesse feat to apply your Dexterity modifier instead of your Strength modifier to attack rolls with a whip sized for you, even though it isn''t a light weapon for you.\n', 1, 2, 1, 1, 0, 20, 2, 2, 0, 0, 1, 1, 56, 0 );
INSERT INTO weapon VALUES ( 55, 'Axe, orc double', 'An orc double axe is a double weapon. You can fight with it as if fighting with two weapons, but if you do, you incur all the normal attack penalties associated with fighting with two weapons, just as if you were using a one-handed weapon and a light weapon.\nA creature wielding an orc double axe in one hand can''t use it as a double weapon - only one end of the weapon can be used in any given round.', 60, 15, 1, 4, 0, 20, 3, 2, 0, 0, 2, 2, 57, 0 );
INSERT INTO weapon VALUES ( 56, 'Chain, piked', 'A spiked chain has reach, so you can strike opponents 10 feet away with it. In addition, unlike most other weapons with reach, it can be used against an adjacent foe.\nYou can make trip attacks with the chain. If you are tripped during your own trip attempt, you can drop the chain to avoid being tripped.\nWhen using a spiked chain, you get a +2 bonus on opposed attack rolls made to disarm an opponent (including the roll to avoid being disarmed if such an attempt fails).\nYou can use the Weapon Finesse feat to apply your Dexterity modifier instead of your Strength modifier to attack rolls with a spiked chain sized for you, even though it isn''t a light weapon for you.', 25, 10, 2, 2, 0, 20, 2, 2, 0, 0, 2, 1, 58, 0 );
INSERT INTO weapon VALUES ( 57, 'Flail, dire', 'A dire flail is a double weapon. You can fight with it as if fighting with two weapons, but if you do, you incur all the normal attack penalties associated with fighting with two weapons, just as if you were using a one-handed weapon and a light weapon. A creature wielding a dire flail in one hand can''t use it as a double weapon -  only one end of the weapon can be used in any given round.\nWhen using a dire flail, you get a +2 bonus on opposed attack rolls made to disarm an enemy (including the opposed attack roll to avoid being disarmed if such an attempt fails).\nYou can also use this weapon to make trip attacks. If you are tripped during your own trip attempt, you can drop the dire flail to avoid being tripped.\n', 90, 10, 1, 4, 0, 20, 2, 2, 0, 0, 2, 2, 59, 0 );
INSERT INTO weapon VALUES ( 58, 'Hammer, gnome hooked', 'A gnome hooked hammer is a double weapon. You can fight with it as if fighting with two weapons, but if you do, you incur all the normal attack penalties associated with fighting with two weapons, just as if you were using a one-handed weapon and a light weapon. The hammer''s blunt head is a bludgeoning weapon that deals 1d6 points of damage (crit x3). Its hook is a piercing weapon that deals 1d4 points of damage (crit x4). You can use either head as the primary weapon. The other head is the offhand weapon. A creature wielding a gnome hooked hammer in one hand can''t use it as a double weapon - only one end of the weapon can be used in any given round.\nYou can use a gnome hooked hammer to make trip attacks. If you are tripped during your own trip attempt, you can drop the gnome hooked hammer to avoid being tripped.\nGnomes treat gnome hooked hammers as martial weapons.\n', 20, 6, 1, 4, 0, 20, 3, 2, 0, 0, 2, 2, 60, 0 );
INSERT INTO weapon VALUES ( 59, 'Sword, two-bladed', 'A two-bladed sword is a double weapon. You can fight with it as if fighting with two weapons, but if you do, you incur all the normal attack penalties associated with fighting with two weapons, just as if you were using a one-handed weapon and a light weapon. A creature wielding a two-bladed sword in one hand can''t use it as a double weapon - only one end of the weapon can be used in any given round.', 100, 10, 1, 4, 0, 19, 2, 2, 0, 0, 2, 2, 61, 0 );
INSERT INTO weapon VALUES ( 60, 'Urgrosh, dwarven', 'A dwarven urgrosh is a double weapon. You can fight with it as if fighting with two weapons, but if you do, you incur all the normal attack penalties associated with fighting with two weapons, just as if you were using a one-handed weapon and a light weapon. The urgrosh''s axe head is a slashing weapon that deals 1d8 points of damage. Its spear head is a piercing weapon that deals 1d6 points of damage. You can use either head as the primary weapon. The other is the off-hand weapon. A creature wielding a dwarven urgrosh in one hand can''t use it as a double weapon - only one end of the weapon can be used in any given round.\nIf you use a ready action to set an urgrosh against a charge, you deal double damage if you score a hit against a charging character. If you use an urgrosh against a charging character, the spear head is the part of the weapon that deals damage.\nDwarves treat dwarven urgroshes as martial weapons.\n', 50, 12, 1, 4, 0, 20, 3, 2, 0, 0, 2, 2, 62, 0 );
INSERT INTO weapon VALUES ( 61, 'Bolas', 'You can use this weapon to make a ranged trip attack against an opponent. You can''t be tripped during your own trip attempt when using a set of bolas.', 5, 2, 1, 2, 0, 20, 2, 2, 0, 0, 4, 3, 63, 10 );
INSERT INTO weapon VALUES ( 62, 'Crossbow, hand', 'You can draw a hand crossbow back by hand. Loading a hand crossbow is a move action that provokes attacks of opportunity.\nYou can shoot, but not load, a hand crossbow with one hand at no penalty. You can shoot a hand crossbow with each hand, but you take a penalty on attack rolls as if attacking with two light weapons.', 100, 2, 1, 2, 0, 19, 2, 2, 0, 1, 4, 4, 64, 30 );
INSERT INTO weapon VALUES ( 63, 'Crossbow, repeating heavy', 'The repeating crossbow (whether heavy or light) holds 5 crossbow bolts. As long as it holds bolts, you can reload it by pulling the reloading lever (a free action). Loading a new case of 5 bolts is a full-round action that provokes attacks of opportunity.\nYou can fire a repeating crossbow with one hand or fire a repeating crossbow in each hand in the same manner as you would a normal crossbow of the same size. However, you must fire the weapon with two hands in order to use the reloading lever, and you must use two hands to load a new case of bolts.', 400, 12, 1, 5, 0, 19, 2, 2, 0, 1, 4, 4, 65, 120 );
INSERT INTO weapon VALUES ( 64, 'Crossbow, repeating light', 'The repeating crossbow (whether heavy or light) holds 5 crossbow bolts. As long as it holds bolts, you can reload it by pulling the reloading lever (a free action). Loading a new case of 5 bolts is a full-round action that provokes attacks of opportunity.\nYou can fire a repeating crossbow with one hand or fire a repeating crossbow in each hand in the same manner as you would a normal crossbow of the same size. However, you must fire the weapon with two hands in order to use the reloading lever, and you must use two hands to load a new case of bolts.', 250, 6, 1, 4, 0, 19, 2, 2, 0, 1, 4, 4, 66, 80 );
INSERT INTO weapon VALUES ( 65, 'Shuriken', 'A shuriken is a special monk weapon. This designation gives a monk wielding shuriken special options. A shuriken can''t be used as a melee weapon.\nAlthough they are thrown weapons, shuriken are treated as ammunition for the purposes of drawing them, crafting masterwork or otherwise special versions of them and what happens to them after they are thrown.\n', 0.2, 0.1, 1, 0, 0, 20, 2, 2, 0, 1, 3, 3, 68, 10 );
INSERT INTO weapon VALUES ( 66, 'Bolts, crossbow (10)', 'A crossbow bolt used as a melee weapon is treated as a light improvised weapon (-4 penalty on attack rolls) and deals damage as a dagger of its size (crit x2). Bolts come in a wooden case that holds 10 bolts (or 5, for a repeating crossbow). A bolt that hits its target is destroyed, one that misses has a 50% chance of being destroyed or lost.', 1, 1, 0, 0, 0, 0, 0, 3, 0, 1, 3, 5, 69, 0 );
INSERT INTO weapon VALUES ( 67, 'Bullets, sling (10)', 'Bullets come in a leather pouch that holds 10 bullets. A bullet that hits its target is destroyed, one that misses has a 50% chance of being destroyed or lost.', 0.1, 1, 0, 0, 0, 0, 0, 3, 0, 1, 3, 5, 69, 0 );
INSERT INTO weapon VALUES ( 68, 'Arrows (20)', 'An arrow used as a melee weapon is treated as a light improvised weapon (-4 penalty on attack rolls) and deals damage as a dagger of its size (critical multiplier x2). Arrows come in a leather quiver that holds 20 arrows. An arrow that hits its target is destroyed, one that misses has a 50% chance of being destroyed or lost.', 1, 3, 0, 0, 0, 0, 0, 3, 0, 1, 3, 5, 69, 0 );
INSERT INTO weapon VALUES ( 69, 'Adamantine Battleaxe', 'This nonmagical axe is made out of adamantine. As a masterwork weapon, it has a +1 enhancement bonus on attack rolls.', 3010, 6, 1, 4, 0, 20, 3, 1, 0, 0, 1, 0, 26, 0 );
INSERT INTO weapon VALUES ( 70, 'Adamantine Dagger', 'This nonmagical dagger is made out of adamantine. As a masterwork weapon, it has a +1 enhancement bonus on attack rolls.', 3002, 1, 1, 2, 0, 19, 2, 0, 0, 0, 1, 0, 2, 10 );
INSERT INTO weapon VALUES ( 71, 'Assassin Dagger', 'This wicked-looking, curved +2 dagger provides a +1 bonus to the DC of a Fortitude save forced by the death attack of an assassin.', 18302, 1, 1, 2, 2, 19, 2, 0, 2, 0, 1, 0, 2, 10 );
INSERT INTO weapon VALUES ( 72, 'Dagger of Venom', 'This black +1 dagger has a serrated edge. It allows the wielder to use a poison effect (as the spell, save DC 14) upon a creature struck by the blade once per day. The wielder can decide to use the power after he has struck. Doing so is a free action, but the poison effect must be invoked in the same round that the dagger strikes.', 8302, 1, 1, 2, 1, 19, 2, 0, 2, 0, 1, 0, 2, 10 );
INSERT INTO weapon VALUES ( 73, 'Dwarven Thrower', 'This weapon commonly functions as a +2 warhammer. In the hands of a dwarf, the warhammer gains an additional +1 enhancement bonus (for a total enhancement bonus of +3) and gains the returning special ability. It can be hurled with a 30-foot range increment. When hurled, it deals an extra 2d8 points of damage against giants or an extra 1d8 points of damage against any other target.', 60312, 5, 1, 4, 2, 20, 3, 1, 2, 0, 1, 3, 34, 30 );
INSERT INTO weapon VALUES ( 74, 'Flame Tongue', 'This is a +1 flaming burst longsword. Once per day, the sword can blast forth a fiery ray at any target within 30 feet as a ranged touch attack. The ray deals 4d6 points of fire damage on a successful hit.', 10515, 4, 1, 4, 1, 19, 2, 1, 2, 0, 1, 0, 28, 0 );
INSERT INTO weapon VALUES ( 75, 'Frost Brand', 'This +3 frost greatsword sheds light as a torch when the temperature drops below 0�F. At such times it cannot be concealed when drawn, nor can its light be shut off. Its wielder is protected from fire, the sword absorbs the first 10 points of fire damage each round that the wielder would otherwise take.\nA frost brand extinguishes all nonmagical fires in its area. As a standard action, it can also dispel lasting fire spells, but not instantaneous effects, though you must succeed on a dispel check (1d20 +14) against each spell to dispel it. The DC to dispel such spells is 11 + the caster level of the fire spell.\n', 27375, 8, 2, 3, 3, 19, 2, 1, 2, 0, 2, 0, 40, 0 );
INSERT INTO weapon VALUES ( 76, 'Holy Avenger', 'This +2 cold iron longsword becomes a +5 holy cold iron longsword in the hands of a paladin.\nIt provides spell resistance of 5 + the paladin''s level to the wielder and anyone adjacent to her. It also enables the wielder to use greater dispel magic (once per round as a standard action) at the class level of the paladin. (Only the area dispel is possible, not the targeted dispel or counterspell versions of greater dispel magic.)\n', 12063, 4, 1, 4, 2, 19, 2, 1, 2, 0, 1, 0, 28, 0 );
INSERT INTO weapon VALUES ( 77, 'Javelin of Lightning', 'This javelin becomes a 5d6 lightning bolt when thrown (Reflex DC 14 half ). It is consumed in the attack.', 1500, 2, 5, 3, 0, 20, 2, 0, 2, 1, 4, 3, 15, 0 );
INSERT INTO weapon VALUES ( 78, 'Life-Drinker', 'This +1 greataxe is favored by undead and constructs, who do not suffer its drawback. A life-drinker bestows two negative levels on its target whenever it deals damage, just as if its target had been struck by an undead creature. One day after being struck, subjects must make a DC 16 Fortitude save for each negative level or lose a character level.\nEach time a life-drinker deals damage to a foe, it also bestows one negative level on the wielder. Any negative level gained by the wielder in this fashion lasts for 1 hour.\n', 40320, 12, 1, 6, 1, 20, 3, 1, 0, 0, 2, 0, 37, 0 );
INSERT INTO weapon VALUES ( 79, 'Luck Blade (0 wishes)', 'This +2 short sword gives its possessor a +1 luck bonus on all saving throws. Its possessor also gains the power of good fortune, usable once per day. This extraordinary ability allows its possessor to reroll one roll that she just made. She must take the result of the reroll, even if it''s worse than the original roll. In addition, a luck blade may contain up to three wishes (when randomly rolled, a luck blade holds 1d4-1 wishes, minimum 0). When the last wish is used, the sword remains a +2 short sword, still grants the +1 luck bonus, and still grants its reroll power.', 22060, 2, 1, 3, 2, 19, 2, 1, 2, 0, 0, 0, 25, 0 );
INSERT INTO weapon VALUES ( 80, 'Luck Blade (1 wish)', 'This +2 short sword gives its possessor a +1 luck bonus on all saving throws. Its possessor also gains the power of good fortune, usable once per day. This extraordinary ability allows its possessor to reroll one roll that she just made. She must take the result of the reroll, even if it''s worse than the original roll. In addition, a luck blade may contain up to three wishes (when randomly rolled, a luck blade holds 1d4-1 wishes, minimum 0). When the last wish is used, the sword remains a +2 short sword, still grants the +1 luck bonus, and still grants its reroll power.', 62360, 2, 1, 3, 2, 19, 2, 1, 2, 0, 0, 0, 25, 0 );
INSERT INTO weapon VALUES ( 81, 'Luck Blade (2 wishes)', 'This +2 short sword gives its possessor a +1 luck bonus on all saving throws. Its possessor also gains the power of good fortune, usable once per day. This extraordinary ability allows its possessor to reroll one roll that she just made. She must take the result of the reroll, even if it''s worse than the original roll. In addition, a luck blade may contain up to three wishes (when randomly rolled, a luck blade holds 1d4-1 wishes, minimum 0). When the last wish is used, the sword remains a +2 short sword, still grants the +1 luck bonus, and still grants its reroll power.', 102660, 2, 1, 3, 2, 19, 2, 1, 2, 0, 0, 0, 25, 0 );
INSERT INTO weapon VALUES ( 82, 'Luck Blade (3 wishes)', 'This +2 short sword gives its possessor a +1 luck bonus on all saving throws. Its possessor also gains the power of good fortune, usable once per day. This extraordinary ability allows its possessor to reroll one roll that she just made. She must take the result of the reroll, even if it''s worse than the original roll. In addition, a luck blade may contain up to three wishes (when randomly rolled, a luck blade holds 1d4-1 wishes, minimum 0). When the last wish is used, the sword remains a +2 short sword, still grants the +1 luck bonus, and still grants its reroll power.', 142960, 2, 1, 3, 2, 19, 2, 1, 2, 0, 0, 0, 25, 0 );
INSERT INTO weapon VALUES ( 83, 'Mace of Smiting', 'This +3 adamantine heavy mace has a +5 enhancement bonus against constructs, and any critical hit dealt to a construct completely destroys it (no saving throw). A critical hit dealt to an outsider deals x4 damage rather than x2.', 75312, 8, 1, 4, 3, 20, 2, 0, 2, 0, 1, 0, 6, 0 );
INSERT INTO weapon VALUES ( 84, 'Mace of Terror', 'On command, this +2 heavy mace causes the wielder''s clothes and appearance to transform into an illusion of darkest horror such that living creatures in a 30-foot cone become panicked as if by a fear spell (Will DC 16 partial). They take a -2 morale penalty on saving throws, and they flee from the wielder. The wielder may use this ability up to three times per day. ', 38552, 8, 1, 4, 2, 20, 2, 0, 2, 0, 1, 0, 6, 0 );
INSERT INTO weapon VALUES ( 85, 'Cold Iron Longsword', 'This nonmagical longsword is crafted out of cold iron. As a masterwork weapon, it has a +1 enhancement bonus on attack rolls.', 330, 4, 1, 4, 0, 19, 2, 1, 1, 0, 1, 0, 28, 0 );
INSERT INTO weapon VALUES ( 86, 'Nine Lives Stealer', 'This longsword always performs as a +2 longsword, but it also has the power to draw the life force from an opponent. It can do this nine times before the ability is lost. At that point, the sword becomes a simple +2 longsword (with a hint of evil about it). A critical hit must be dealt for the sword''s death-dealing ability to function, and this weapon has no effect on creatures not subject to critical hits. The victim is entitled to a DC 20 Fortitude save to avoid death. If the save is successful, the sword''s death-dealing ability does not function, no use of the ability is expended, and normal critical damage is determined. This sword is evil, and any good character attempting to wield it gains two negative levels. These negative levels remain as long as the sword is in hand and disappear when the sword is no longer wielded. These negative levels never result in actual level loss, but they cannot be overcome in any way (including restoration spells) while the sword is wielded.', 23057, 4, 1, 4, 2, 19, 2, 1, 2, 0, 1, 0, 28, 0 );
INSERT INTO weapon VALUES ( 87, 'Oathbow', 'Of elven make, this white +2 composite longbow (+2 Str bonus) whispers ''Swift defeat to my enemies'' in Elven when nocked and pulled. Once per day, if the firer swears aloud to slay her target (a free action), the bow''s whisper becomes the low shout ''Swift death to those who have wronged me.'' Against such a sworn enemy, the bow has a +5 enhancement bonus, and arrows launched from it deal an additional 2d6 points of damage (and x4 on a critical hit instead of the normal x3). However, the bow is treated as only a masterwork weapon against all foes other than the sworn enemy, and the wielder takes a -1 penalty on attack rolls with any weapon other than the oathbow. These bonuses and penalties last for seven days or until the sworn enemy is slain or destroyed by the wielder of the oathbow, whichever comes first.\nThe oathbow may only have one sworn enemy at a time. Once the wielder swears to slay a target, he cannot make a new oath until he has slain that target or seven days have passed. Even if the wielder slays the sworn enemy on the same day that he makes the oath, he cannot activate the oathbow''s special power again until 24 hours have passed from the time he made the oath.\n', 25600, 3, 1, 4, 2, 20, 3, 1, 2, 1, 5, 4, 47, 110 );
INSERT INTO weapon VALUES ( 88, 'Rapier of Puncturing', 'Three times per day, this +2 wounding rapier allows the wielder to make a touch attack with the weapon that deals 1d6 points of Constitution damage by draining blood. Creatures immune to critical hits are immune to the Constitution damage dealt by this weapon.', 50320, 2, 1, 3, 2, 18, 2, 1, 2, 0, 1, 0, 30, 0 );
INSERT INTO weapon VALUES ( 89, 'Screaming Bolt', 'One of these +2 bolts screams when fired, forcing all enemies of the wielder within 20 feet of the path of the bolt to succeed on a DC 14 Will save or become shaken. This is a mind-affecting fear effect.', 267, 0.1, 0, 0, 0, 0, 0, 3, 2, 1, 3, 5, 69, 0 );
INSERT INTO weapon VALUES ( 90, 'Shatterspike', 'Wielders without the Improved Sunder feat use Shatterspike as a +1 longsword only, wielders with the Improved Sunder feat add a +4 bonus (including the sword''s +1 enhancement bonus) to the opposed roll when attempting to strike a foe''s weapon. If successful, Shatterspike deals 1d8+4 points of damage plus the wielder''s Strength modifier to the target weapon (the target weapon''s hardness must still be overcome with each hit). Shatterspike can damage weapons with an enhancement bonus of +4 or lower.', 4315, 4, 1, 4, 1, 19, 2, 1, 2, 0, 1, 0, 28, 0 );
INSERT INTO weapon VALUES ( 91, 'Shifter Sorrow', 'This +1/+1 two-bladed sword has blades of alchemical silver. The weapon deals an extra 2d6 points of damage against any creature with the shapechanger subtype. When a shapechanger or a creature in an alternate form (such as a druid using wild shape) is struck by the weapon, it must make a DC 15 Will save or return to its natural form.', 12780, 10, 1, 4, 1, 19, 2, 3, 2, 0, 2, 2, 61, 0 );
INSERT INTO weapon VALUES ( 92, 'Silver Dagger', 'This masterwork alchemical silver dagger is nonmagical. As a masterwork weapon, it has a +1 enhancement bonus on attack rolls.', 322, 1, 1, 2, 0, 19, 2, 0, 1, 0, 0, 0, 2, 10 );
INSERT INTO weapon VALUES ( 93, 'Slaying Arrow', 'This +1 arrow is keyed to a particular type or subtype of creature. If it strikes such a creature, the target must make a DC 20 Fortitude save or die (or, in the case of unliving targets, be destroyed) instantly. Note that even creatures normally exempt from Fortitude saves (undead and constructs) are subject to this attack. When keyed to a living creature, this is a death effect (and thus death ward protects a target). To determine the type or subtype of creature the arrow is keyed to, roll on the table below.\nA greater slaying arrow functions just like a normal slaying arrow, but the DC to avoid the death effect is 23.\n', 2282, 0.15, 0, 0, 0, 0, 0, 3, 2, 1, 3, 5, 69, 0 );
INSERT INTO weapon VALUES ( 94, 'Slaying Arrow, greater', 'This +1 arrow is keyed to a particular type or subtype of creature. If it strikes such a creature, the target must make a DC 20 Fortitude save or die (or, in the case of unliving targets, be destroyed) instantly. Note that even creatures normally exempt from Fortitude saves (undead and constructs) are subject to this attack. When keyed to a living creature, this is a death effect (and thus death ward protects a target). To determine the type or subtype of creature the arrow is keyed to, roll on the table below.\nA greater slaying arrow functions just like a normal slaying arrow, but the DC to avoid the death effect is 23.\n', 4057, 0.15, 0, 0, 0, 0, 0, 3, 2, 1, 3, 5, 69, 0 );
INSERT INTO weapon VALUES ( 95, 'Sleep Arrow', 'This +1 arrow is painted white and has white fletching. If it strikes a foe so that it would normally deal damage, it instead bursts into magical energy that deals nonlethal damage (in the same amount as would be lethal damage) and forces the target to make a DC 11 Will save or fall asleep.', 132, 0.15, 0, 0, 0, 0, 0, 3, 2, 1, 3, 5, 69, 0 );
INSERT INTO weapon VALUES ( 96, 'Sun Blade', 'This sword is the size of a bastard sword. However, a sun blade is wielded as if it were a short sword with respect to weight and ease of use. (In other words, the weapon appears to all viewers to be a bastard sword, and deals bastard sword damage, but the wielder feels and reacts as if the weapon were a short sword.) Any individual able to use either a bastard sword or a short sword with proficiency is proficient in the use of a sun blade. Likewise, Weapon Focus and Weapon Specialization in short sword and bastard sword apply equally, but the benefits of those feats do not stack.\nIn normal combat, the glowing golden blade of the weapon is equal to a +2 bastard sword. Against evil creatures, its enhancement bonus is +4. Against Negative Energy Plane creatures or undead creatures, the sword deals double damage (and x3 on a critical hit instead of the usual x2).\nThe blade also has a special sunlight power. Once per day, the wielder can swing the blade vigorously above her head while speaking a command word. The sunblade then sheds a bright yellow radiance that is like full daylight. The radiance begins shining in a 10-foot radius around the sword wielder and extends outward at 5 feet per round for 10 rounds thereafter, to create a globe of light with a 60-foot radius. When the wielder stops swinging, the radiance fades to a dim glow that persists for another minute before disappearing entirely. All sun blades are of good alignment, and any evil creature attempting to wield one gains one negative level. The negative level remains as long as the sword is in hand and disappears when the sword is no longer wielded. This negative level never results in actual level loss, but it cannot be overcome in any way (including restoration spells) while the sword is wielded.\n', 50335, 2, 1, 5, 2, 19, 2, 2, 2, 0, 1, 0, 54, 0 );
INSERT INTO weapon VALUES ( 97, 'Sword of Life Stealing', 'This black iron +2 longsword bestows a negative level when it deals a critical hit. The sword wielder gains 1d6 temporary hit points each time a negative level is bestowed on another. These temporary hit points last for 24 hours. One day after being struck, subjects must make a DC 16 Fortitude save for each negative level or lose a character level.', 25715, 4, 1, 4, 2, 19, 2, 1, 2, 0, 1, 0, 28, 0 );
INSERT INTO weapon VALUES ( 98, 'Sword of the Planes', 'This longsword has an enhancement bonus of +1 on the Material Plane, but on any Elemental Plane its enhancement bonus increases to +2. (The +2 enhancement bonus also applies on the Material Plane when the weapon is used against elementals.) It operates as a +3 longsword on the Astral Plane or the Ethereal Plane or when used against opponents native to either of those planes. On any other plane, or against any outsider, it functions as a +4 longsword.', 22315, 4, 1, 4, 1, 19, 2, 1, 2, 0, 1, 0, 28, 0 );
INSERT INTO weapon VALUES ( 99, 'Sword of Subtlety', 'A +1 short sword with a thin, dull gray blade, this weapon provides a +4 bonus on its wielder''s attack and damage rolls when he is making a sneak attack with it.', 22310, 2, 1, 3, 1, 19, 2, 1, 2, 0, 0, 0, 25, 0 );
INSERT INTO weapon VALUES ( 100, 'Sylvan Scimitar', 'This +3 scimitar, when used outdoors in a temperate climate, grants its wielder the use of the Cleave feat and deals an extra 1d6 points of damage.', 47315, 4, 1, 3, 3, 18, 2, 2, 2, 0, 1, 0, 31, 0 );
INSERT INTO weapon VALUES ( 101, 'Trident of Fish Command', 'The magical properties of this +1 trident with a 6-foot-long haft enable its wielder to charm up to 14 HD of aquatic animals (Will DC 16 negates, animals get a +5 bonus if currently under attack by the wielder or his allies), no two of which can be more than 30 feet apart. The wielder can use this effect up to three times per day. The wielder can communicate with the animals as if using a speak with animals spell. Animals making their saving throw are free of control, but they will not approach within 10 feet of the trident. The trident can be used up to three times per day.', 18650, 4, 1, 4, 1, 20, 2, 1, 2, 0, 1, 0, 33, 10 );
INSERT INTO weapon VALUES ( 102, 'Trident of Warning', 'A weapon of this type enables its wielder to determine the location, depth, kind, and number of aquatic predators within 680 feet. A trident of warning must be grasped and pointed in order for the character using it to gain such information, and it requires 1 round to scan a hemisphere with a radius of 680 feet. The weapon is otherwise a +2 trident.', 10115, 4, 1, 4, 2, 20, 2, 1, 2, 0, 1, 0, 33, 10 );
INSERT INTO weapon VALUES ( 103, 'Unarmed strike', 'A Medium character deals 1d3 points of nonlethal damage with an unarmed strike. A Small character deals 1d2 points of nonlethal damage. A monk or any character with the Improved Unarmed Strike feat can deal lethal or nonlethal damage with unarmed strikes, at her option. The damage from an unarmed strike is considered weapon damage for the purposes of effects that give you a bonus on weapon damage rolls.\nAn unarmed strike is always considered a light weapon. Therefore, you can use the Weapon Finesse feat to apply your Dexterity modifier instead of your Strength modifier to attack rolls with an unarmed strike.\n', 0, 0, 1, 1, 0, 20, 2, 0, 0, 0, 0, 0, 1, 0 );
INSERT INTO weapon VALUES ( 104, 'Shield, light', 'You can bash with a shield instead of using it for defense. See Armor for details.', 0, 0, 1, 1, 0, 20, 2, 1, 0, 0, 0, 0, 23, 0 );
INSERT INTO weapon VALUES ( 105, 'Spiked armor', 'You can outfit your armor with spikes, which can deal damage in a grapple or as a separate attack. See Armor for details.', 0, 0, 1, 3, 0, 20, 2, 1, 0, 0, 0, 0, 24, 0 );
INSERT INTO weapon VALUES ( 106, 'Spiked shield, light', 'You can bash with a spiked shield instead of using it for defense. See Armor for details.', 0, 0, 1, 2, 0, 20, 2, 1, 0, 0, 0, 0, 23, 0 );
INSERT INTO weapon VALUES ( 107, 'Shield, heavy', 'You can bash with a shield instead of using it for defense. See Armor for details.', 0, 0, 1, 2, 0, 20, 2, 1, 0, 0, 1, 0, 32, 0 );
INSERT INTO weapon VALUES ( 108, 'Spiked shield, heavy', 'You can bash with a spiked shield instead of using it for defense. See Armor for details.', 0, 0, 1, 3, 0, 20, 2, 1, 0, 0, 1, 0, 32, 0 );
INSERT INTO weapon VALUES ( 109, 'Net', 'A net is used to entangle enemies. When you throw a net, you make a ranged touch attack against your target. A net''s maximum range is 10 feet. If you hit, the target is entangled. An entangled creature takes a -2 penalty on attack rolls and a -4 penalty on Dexterity, can move at only half speed, and cannot charge or run. If you control the trailing rope by succeeding on an opposed Strength check while holding it, the entangled creature can move only within the limits that the rope allows. If the entangled creature attempts to cast a spell, it must make a DC 15 Concentration check or be unable to cast the spell.\nAn entangled creature can escape with a DC 20 Escape Artist check (a full-round action). The net has 5 hit points and can be burst with a DC 25 Strength check (also a full-round action).\nA net is useful only against creatures within one size category of you.\nA net must be folded to be thrown effectively. The first time you throw your net in a fight, you make a normal ranged touch attack roll. After the net is unfolded, you take a -4 penalty on attack rolls with it. It takes 2 rounds for a proficient user to fold a net and twice that long for a nonproficient one to do so.\n', 20, 6, 0, 0, 0, 0, 0, 2, 0, 1, 4, 3, 67, 0 );


DELETE FROM armor WHERE id <= 37;

INSERT INTO armor VALUES ( 0, 'Padded', '', 5, 10, 1, 0, 0, 0 );
INSERT INTO armor VALUES ( 1, 'Leather', '', 10, 15, 2, 0, 0, 0 );
INSERT INTO armor VALUES ( 2, 'Studded Leather', '', 25, 20, 3, -1, 0, 0 );
INSERT INTO armor VALUES ( 3, 'Chain Shirt', 'A chain shirt comes with a steel cap.', 100, 25, 4, -2, 0, 0 );
INSERT INTO armor VALUES ( 4, 'Hide', '', 15, 25, 3, -3, 1, 0 );
INSERT INTO armor VALUES ( 5, 'Scale Mail', 'The suit includes gauntlets.', 50, 30, 4, -4, 1, 0 );
INSERT INTO armor VALUES ( 6, 'Chain Mail', 'The suit includes gauntlets.', 150, 40, 5, -5, 1, 0 );
INSERT INTO armor VALUES ( 7, 'Breastplate', 'It comes with a helmet and greaves.', 200, 30, 5, -4, 1, 0 );
INSERT INTO armor VALUES ( 8, 'Splint Mail', 'The suit includes gauntlets.', 200, 45, 6, -7, 2, 0 );
INSERT INTO armor VALUES ( 9, 'Banded Mail', 'The suit includes gauntlets.', 250, 35, 6, -6, 2, 0 );
INSERT INTO armor VALUES ( 10, 'Half-Plate', 'The suit includes gauntlets.', 600, 50, 7, -7, 2, 0 );
INSERT INTO armor VALUES ( 11, 'Full Plate', 'The suit includes gauntlets, heavy leather boots, a visored helmet, and a thick layer of padding that is worn underneath the armor. Each suit of full plate must be individually fitted to its owner by a master armorsmith, although a captured suit can be resized to fit a new owner at a cost of 200 to 800 (2d4x100) gold pieces.', 1500, 50, 8, -6, 2, 0 );
INSERT INTO armor VALUES ( 12, 'Buckler', 'This small metal shield is worn strapped to your forearm. You can use a bow or crossbow without penalty while carrying it. You can also use your shield arm to wield a weapon (whether you are using an off-hand weapon or using your off hand to help wield a two-handed weapon), but you take a -1 penalty on attack rolls while doing so. This penalty stacks with those that may apply for fighting with your off hand and for fighting with two weapons. In any case, if you use a weapon in your off hand, you don''t get the buckler''s AC bonus for the rest of the round.\nYou can''t bash someone with a buckler.\n', 15, 5, 1, -1, 3, 0 );
INSERT INTO armor VALUES ( 13, 'Light Wooden Shield', 'You strap a shield to your forearm and grip it with your hand. A light shield''s weight lets you carry other items in that hand, although you cannot use weapons with it.\nWooden or Steel: Wooden and steel shields offer the same basic protection, though they respond differently to special attacks.\nShield Bash Attacks: You can bash an opponent with a light shield, using it as an off-hand weapon. See Table: Weapons for the damage dealt by a shield bash. Used this way, a light shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a light shield as a light weapon. If you use your shield as a weapon, you lose its AC bonus until your next action (usually until the next round). An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.\n', 3, 5, 1, -1, 3, 0 );
INSERT INTO armor VALUES ( 14, 'Light Steel Shield', 'You strap a shield to your forearm and grip it with your hand. A light shield''s weight lets you carry other items in that hand, although you cannot use weapons with it.\nWooden or Steel: Wooden and steel shields offer the same basic protection, though they respond differently to special attacks.\nShield Bash Attacks: You can bash an opponent with a light shield, using it as an off-hand weapon. See Table: Weapons for the damage dealt by a shield bash. Used this way, a light shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a light shield as a light weapon. If you use your shield as a weapon, you lose its AC bonus until your next action (usually until the next round). An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.\n', 9, 6, 1, -1, 3, 0 );
INSERT INTO armor VALUES ( 15, 'Heavy Wooden Shield', 'You strap a shield to your forearm and grip it with your hand. A heavy shield is so heavy that you can''t use your shield hand for anything else.\nWooden or Steel: Wooden and steel shields offer the same basic protection, though they respond differently to special attacks.\nShield Bash Attacks: You can bash an opponent with a heavy shield, using it as an off-hand weapon. See Table: Weapons for the damage dealt by a shield bash. Used this way, a heavy shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a heavy shield as a one-handed weapon. If you use your shield as a weapon, you lose its AC bonus until your next action (usually until the next round). An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.\n', 7, 10, 2, -2, 3, 0 );
INSERT INTO armor VALUES ( 16, 'Heavy Steel Shield', 'You strap a shield to your forearm and grip it with your hand. A heavy shield is so heavy that you can''t use your shield hand for anything else.\nWooden or Steel: Wooden and steel shields offer the same basic protection, though they respond differently to special attacks.\nShield Bash Attacks: You can bash an opponent with a heavy shield, using it as an off-hand weapon. See Table: Weapons for the damage dealt by a shield bash. Used this way, a heavy shield is a martial bludgeoning weapon. For the purpose of penalties on attack rolls, treat a heavy shield as a one-handed weapon. If you use your shield as a weapon, you lose its AC bonus until your next action (usually until the next round). An enhancement bonus on a shield does not improve the effectiveness of a shield bash made with it, but the shield can be made into a magic weapon in its own right.\n', 20, 15, 2, -2, 3, 0 );
INSERT INTO armor VALUES ( 17, 'Tower Shield', 'This massive wooden shield is nearly as tall as you are. In most situations, it provides the indicated shield bonus to your AC. However, you can instead use it as total cover, though you must give up your attacks to do so. The shield does not, however, provide cover against targeted spells, a spellcaster can cast a spell on you by targeting the shield you are holding. You cannot bash with a tower shield, nor can you use your shield hand for anything else.\nWhen employing a tower shield in combat, you take a -2 penalty on attack rolls because of the shield''s encumbrance.\n', 30, 45, 4, -10, 3, 0 );
INSERT INTO armor VALUES ( 18, 'Adamantine Breastplate', 'This nonmagical breastplate is made of adamantine, giving its wearer damage reduction of 2/-.', 10200, 30, 5, -4, 1, 0 );
INSERT INTO armor VALUES ( 19, 'Banded Mail of Luck', 'Ten 100-gp gems adorn this +3 banded mail. Once per week, the armor allows its wearer to require that an attack roll made against him be rerolled. He must take whatever consequences come from the second roll. The wearer''s player must decide whether to have the attack roll rerolled before damage is rolled.', 18900, 35, 9, -3, 2, 2 );
INSERT INTO armor VALUES ( 20, 'Breastplate of Command', 'This finely crafted +2 breastplate radiates a powerful aura of magic. When worn, the armor bestows a dignified and commanding aura upon its owner. The wearer gains a +2 competence bonus on all Charisma checks, including turning checks and Charisma-based skill checks. The wearer also gains a +2 competence bonus to his Leadership score. Friendly troops within 360 feet of the user become braver than normal. Since the effect arises in great part from the distinctiveness of the armor, the wearer cannot hide or conceal herself in any way and still have the effect function.', 25400, 30, 7, -2, 1, 2 );
INSERT INTO armor VALUES ( 21, 'Celestial Armor', 'This bright silver or gold +3 chainmail is so fine and light that it can be worn under normal clothing without betraying its presence. It has a maximum Dexterity bonus of +8, an armor check penalty of -2, and an arcane spell failure chance of 15%. It is considered light armor, weighs 20 pounds, and it allows the wearer to use fly on command (as the spell) once per day.', 22400, 20, 8, -2, 0, 2 );
INSERT INTO armor VALUES ( 22, 'Demon Armor', 'This plate armor is fashioned to make the wearer appear to be a demon. The helmet is shaped to look like a horned demon head, and its wearer looks out of the open, tooth-filled mouth. This +4 full plate allows the wearer to make claw attacks that deal 1d10 points of damage, strike as +1 weapons, and afflict the target as if she had been struck by a contagion spell (Fortitude DC 14 negates). Use of contagion requires a normal melee attack with the claws. The ''claws'' are built into the armor''s vambraces and gauntlets. \nThe armor bestows one negative level on any nonevil creature wearing it. This negative level persists as long as the armor is worn and disappears when the armor is removed. The negative level never results in actual level loss, but it cannot be overcome in any way (including restoration spells) while the armor is worn.\n', 52260, 50, 12, -2, 2, 2 );
INSERT INTO armor VALUES ( 23, 'Dragonhide Plate', 'This suit of full plate is made of dragonhide, rather than metal, so druids can wear it. It is otherwise identical to masterwork full plate.', 3300, 50, 8, -6, 2, 0 );
INSERT INTO armor VALUES ( 24, 'Dwarven Plate', 'This full plate is made of adamantine, giving its wearer damage reduction of 3/-.', 16500, 50, 8, -6, 2, 0 );
INSERT INTO armor VALUES ( 25, 'Elven Chain', 'This extremely light chainmail is made of very fine mithral links. Speed while wearing elven chain is 30 feet for Medium creatures, or 20 feet for Small. The armor has an arcane spell failure chance of 20%, a maximum Dexterity bonus of +4, and an armor check penalty of -2. It is considered light armor and weighs 20 pounds.', 4150, 20, 5, -2, 0, 0 );
INSERT INTO armor VALUES ( 26, 'Mithral Full Plate of Speed', 'As a free action, the wearer of this fine set of +1 mithral full plate can activate it, enabling her to act as though affected by a haste spell for up to 10 rounds each day. The duration of the haste effect need not be consecutive rounds.\nSpeed while wearing a suit of mithral full plate is 20 feet for Medium creatures, or 15 feet for Small. The armor has an arcane spell failure chance of 25%, a maximum Dexterity bonus of +3, and an armor check penalty of -3. It is considered medium armor and weighs 25 pounds.\n', 26500, 25, 9, -3, 1, 2 );
INSERT INTO armor VALUES ( 27, 'Mithral Shirt', 'This extremely light chain shirt is made of very fine mithral links. Speed while wearing a mithral shirt is 30 feet for Medium creatures, or 20 feet for Small. The armor has an arcane spell failure chance of 10%, a maximum Dexterity bonus of +6, and no armor check penalty. It is considered light armor and weighs 10 pounds.', 1100, 10, 4, 0, 0, 0 );
INSERT INTO armor VALUES ( 28, 'Plate Armor of the Deep', 'This +1 full plate is decorated with a wave and fish motif. The wearer of plate armor of the deep is treated as unarmored for purposes of Swim checks. The wearer can breathe underwater and can converse with any creature with a language that breathes water.', 24650, 50, 9, -5, 2, 2 );
INSERT INTO armor VALUES ( 29, 'Rhino Hide', 'This +2 hide armor is made from rhinoceros hide. In addition to granting a +2 enhancement bonus to AC, it has a -1 armor check penalty and deals an additional 2d6 points of damage on any successful charge attack made by the wearer, including a mounted charge.', 5165, 25, 5, -1, 1, 2 );
INSERT INTO armor VALUES ( 30, 'Absorbing Shield', 'This +1 heavy steel shield is flat black and seems to absorb light. Once every two days, on command, it can disintegrate an object that it touches, as the spell but requiring a melee touch attack.', 50170, 15, 3, -1, 3, 2 );
INSERT INTO armor VALUES ( 31, 'Caster Shield', 'This +1 light wooden shield has a small leather strip on the back on which a spellcaster can scribe a single spell as on a scroll. A spell so scribed has only half the base raw material cost. Experience point and component costs remain the same. The strip cannot accommodate spells of higher than 3rd level. The strip is reusable.\nA random caster ''s shield has a 50% chance of having a single medium scroll spell on it. The spell is divine (01-80 on d%) or arcane (81-100).\nA caster''s shield has a 5% arcane spell failure chance.\n', 3153, 5, 2, 0, 3, 2 );
INSERT INTO armor VALUES ( 32, 'Darkwood Buckler', 'This nonmagical light wooden shield is made out of darkwood. It has no enhancement bonus, but its construction material makes it lighter than a normal wooden shield. It weighs 2-1/2 pounds and has no armor check penalty.', 205, 2.5, 1, 0, 3, 0 );
INSERT INTO armor VALUES ( 33, 'Darkwood Shield', 'This nonmagical heavy wooden shield is made out of darkwood. It has no enhancement bonus, but its construction material makes it lighter than a normal wooden shield.\nIt weighs 5 pounds and has no armor check penalty.\n', 257, 5, 2, 0, 3, 0 );
INSERT INTO armor VALUES ( 34, 'Lion Shield', 'This +2 heavy steel shield is fashioned to appear to be a roaring lion''s head. Three times per day as a free action, the lion''s head can be commanded to attack (independently of the shield wearer), biting with the wielder''s base attack bonus (including multiple attacks, if the wielder has them) and dealing 2d6 points of damage. This attack is in addition to any actions performed by the wielder.', 9170, 15, 4, 0, 3, 2 );
INSERT INTO armor VALUES ( 35, 'Mithral Heavy Shield', 'This heavy shield is made of mithral and thus is much lighter than a standard steel shield. It has a 5% arcane spell failure chance and no armor check penalty. It weighs 5 pounds.', 1020, 5, 2, 0, 3, 0 );
INSERT INTO armor VALUES ( 36, 'Spined Shield', 'This +1 heavy steel shield is covered in spines. It acts as a normal spiked shield. On command up to three times per day, the shield''s wearer can fire one of the shield''s spines. A fired spine has a +1 enhancement bonus, a range increment of 120 feet, and deals 1d10 points of damage (19-20/x2). Fired spines regenerate each day.', 5580, 15, 3, -1, 3, 2 );
INSERT INTO armor VALUES ( 37, 'Winged Shield', 'This round heavy wooden shield has a +3 enhancement bonus. Small, feathered wings encircle the shield.\nOnce per day it can be commanded to fly (as the spell), carrying the wielder. The shield can carry up to 133 pounds and move at 60 feet per round, or up to 266 pounds and move at 40 feet per round.\n', 17257, 10, 5, 0, 3, 2 );

