UPDATE ability SET name = 'Ability Score Increase' WHERE id = 1031;
UPDATE ability SET name = 'Ability Score Increase (Con +2, Cha +2, Str -2)' WHERE id = 13;
UPDATE ability SET name = 'Ability Score Increase (Con +2, Cha +2, Wis -2)' WHERE id = 1131;
UPDATE ability SET name = 'Ability Score Increase (Con +2, Wis +2, Cha -2)' WHERE id = 1;
UPDATE ability SET name = 'Ability Score Increase (Con +2, Wis +2, Cha -4)' WHERE id = 1122;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Cha +2, Con -2)' WHERE id = 1106;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Cha +2, Con -2)' WHERE id = 1114;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Cha +2, Str -2)' WHERE id = 33;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Cha +2, Str -2)' WHERE id = 1155;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Cha +2, Wis -2)' WHERE id = 1089;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Cha +2, Wis -2)' WHERE id = 1126;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Cha +2, Wis -2)' WHERE id = 1151;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Cha +2, Wis -2)' WHERE id = 1236;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Cha -2)' WHERE id = 1193;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Con +2)' WHERE id = 1148;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Con +2, Cha +2)' WHERE id = 1165;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Int +2, Cha -2)' WHERE id = 1222;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Int +2, Con -2)' WHERE id = 8;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Int +2, Con -2)' WHERE id = 1212;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Int +2, Str -2)' WHERE id = 1182;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Int +2, Wis -2)' WHERE id = 1242;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Str -4, Con -2)' WHERE id = 1161;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Wis +2, Cha -2)' WHERE id = 1231;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Wis +2, Con -2)' WHERE id = 1216;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Wis +2, Str -2)' WHERE id = 1142;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Wis +2, Str -2)' WHERE id = 1227;
UPDATE ability SET name = 'Ability Score Increase (Dex +2, Wis +2, Str -2, Cha -4)' WHERE id = 1202;
UPDATE ability SET name = 'Ability Score Increase (Dex +4,  Str -2, Cha -2)' WHERE id = 1137;
UPDATE ability SET name = 'Ability Score Increase (Int +2, Wis +2, Con -2)' WHERE id = 1188;
UPDATE ability SET name = 'Ability Score Increase (One Ability Score +2)' WHERE id = 21;
UPDATE ability SET name = 'Ability Score Increase (Str +2, Cha +2, Int -2)' WHERE id = 1168;
UPDATE ability SET name = 'Ability Score Increase (Str +2, Cha +2, Int -2)' WHERE id = 1198;
UPDATE ability SET name = 'Ability Score Increase (Str +2, Wis +2, Cha -2)' WHERE id = 1176;
UPDATE ability SET name = 'Ability Score Increase (Str +4, Int -2, Wis -2, Cha -2)' WHERE id = 1171;
UPDATE ability SET name = 'Ability Score Increase (Wis +2, Cha +2)' WHERE id = 1084;
UPDATE ability SET name = 'Ability Score Increase (Wis +2, Cha +2, Con -2)' WHERE id = 1094;


UPDATE ability SET description = 'The eidolon adds +1 to one of its ability scores.' WHERE id = 1031;
UPDATE ability SET description = 'Constitution +2, Charisma +2, Strength -2.' WHERE id = 13;
UPDATE ability SET description = 'Constitution +2, Charisma +2, Wisdom -2.' WHERE id = 1131;
UPDATE ability SET description = 'Constitution +2, Wisdom +2, Charisma -2.' WHERE id = 1;
UPDATE ability SET description = 'Constitution +2, Wisdom +2, Charisma -4.' WHERE id = 1122;
UPDATE ability SET description = 'Dexterity +2, Charisma +2, Constitution -2.' WHERE id = 1106;
UPDATE ability SET description = 'Dexterity +2, Charisma +2, Constitution -2.' WHERE id = 1114;
UPDATE ability SET description = 'Dexterity +2, Charisma +2, Strength -2.' WHERE id = 33;
UPDATE ability SET description = 'Dexterity +2, Charisma +2, Strength -2.' WHERE id = 1155;
UPDATE ability SET description = 'Dexterity +2, Charisma +2, Wisdom -2.' WHERE id = 1089;
UPDATE ability SET description = 'Dexterity +2, Charisma +2, Wisdom -2.' WHERE id = 1126;
UPDATE ability SET description = 'Dexterity +2, Charisma +2, Wisdom -2.' WHERE id = 1151;
UPDATE ability SET description = 'Dexterity +2, Charisma +2, Wisdom -2.' WHERE id = 1236;
UPDATE ability SET description = 'Dexterity +2, Charisma -2.' WHERE id = 1193;
UPDATE ability SET description = 'Dexterity +2, Constitution +2.' WHERE id = 1148;
UPDATE ability SET description = 'Dexterity +2, Constitution +2, Charisma +2.' WHERE id = 1165;
UPDATE ability SET description = 'Dexterity +2, Intelligence +2, Charisma -2.' WHERE id = 1222;
UPDATE ability SET description = 'Dexterity +2, Intelligence +2, Constitution -2.' WHERE id = 8;
UPDATE ability SET description = 'Dexterity +2, Intelligence +2, Constitution -2.' WHERE id = 1212;
UPDATE ability SET description = 'Dexterity +2, Intelligence +2, Strength -2.' WHERE id = 1182;
UPDATE ability SET description = 'Dexterity +2, Intelligence +2, Wisdom -2.' WHERE id = 1242;
UPDATE ability SET description = 'Dexterity +2, Strength -4, Constitution -2.' WHERE id = 1161;
UPDATE ability SET description = 'Dexterity +2, Wisdom +2, Charisma -2.' WHERE id = 1231;
UPDATE ability SET description = 'Dexterity +2, Wisdom +2, Constitution -2.' WHERE id = 1216;
UPDATE ability SET description = 'Dexterity +2, Wisdom +2, Strength -2.' WHERE id = 1142;
UPDATE ability SET description = 'Dexterity +2, Wisdom +2, Strength -2.' WHERE id = 1227;
UPDATE ability SET description = 'Dexterity +2, Wisdom +2, Strength -2, Charisma -4.' WHERE id = 1202;
UPDATE ability SET description = 'Dexterity +4,  Strength -2, Charisma -2.' WHERE id = 1137;
UPDATE ability SET description = 'Intelligence +2, Wisdom +2, Constitution -2.' WHERE id = 1188;
UPDATE ability SET description = 'One Ability Score +2.' WHERE id = 21;
UPDATE ability SET description = 'Strength +2, Charisma +2, Intelligence -2.' WHERE id = 1168;
UPDATE ability SET description = 'Strength +2, Charisma +2, Intelligence -2.' WHERE id = 1198;
UPDATE ability SET description = 'Strength +2, Wisdom +2, Charisma -2.' WHERE id = 1176;
UPDATE ability SET description = 'Strength +4, Intelligence -2, Wisdom -2, Charisma -2.' WHERE id = 1171;
UPDATE ability SET description = 'Wisdom +2, Charisma +2.' WHERE id = 1084;
UPDATE ability SET description = 'Wisdom +2, Charisma +2, Constitution -2.' WHERE id = 1094;


UPDATE image SET id = id + 36 WHERE id > 3;
UPDATE charakter SET image_id = image_id + 36 WHERE image_id > 3;
UPDATE charakter SET thumb_image_id = thumb_image_id + 36 WHERE thumb_image_id > 3;
ALTER TABLE race ADD COLUMN image_id INTEGER NOT NULL DEFAULT 0;


UPDATE race SET image_id = 7 WHERE id = 1;
UPDATE race SET image_id = 10 WHERE id = 2;
UPDATE race SET image_id = 15 WHERE id = 3;
UPDATE race SET image_id = 16 WHERE id = 4;
UPDATE race SET image_id = 29 WHERE id = 5;
UPDATE race SET image_id = 14 WHERE id = 6;
UPDATE race SET image_id = 23 WHERE id = 7;
UPDATE race SET image_id = 0 WHERE id = 8;
UPDATE race SET image_id = 0 WHERE id = 9;
UPDATE race SET image_id = 0 WHERE id = 10;
UPDATE race SET image_id = 9 WHERE id = 11;
UPDATE race SET image_id = 34 WHERE id = 12;
UPDATE race SET image_id = 37 WHERE id = 13;
UPDATE race SET image_id = 38 WHERE id = 14;
UPDATE race SET image_id = 17 WHERE id = 15;
UPDATE race SET image_id = 6 WHERE id = 16;
UPDATE race SET image_id = 12 WHERE id = 17;
UPDATE race SET image_id = 11 WHERE id = 18;
UPDATE race SET image_id = 24 WHERE id = 19;
UPDATE race SET image_id = 28 WHERE id = 20;
UPDATE race SET image_id = 29 WHERE id = 21;
UPDATE race SET image_id = 16 WHERE id = 22;
UPDATE race SET image_id = 33 WHERE id = 23;
UPDATE race SET image_id = 27 WHERE id = 24;
UPDATE race SET image_id = 0 WHERE id = 25;
UPDATE race SET image_id = 18 WHERE id = 26;
UPDATE race SET image_id = 31 WHERE id = 27;
UPDATE race SET image_id = 0 WHERE id = 28;
UPDATE race SET image_id = 36 WHERE id = 29;
UPDATE race SET image_id = 24 WHERE id = 30;
UPDATE race SET image_id = 0 WHERE id = 31;
UPDATE race SET image_id = 0 WHERE id = 32;
UPDATE race SET image_id = 0 WHERE id = 33;
UPDATE race SET image_id = 0 WHERE id = 34;
UPDATE race SET image_id = 0 WHERE id = 35;
UPDATE race SET image_id = 21 WHERE id = 36;
UPDATE race SET image_id = 0 WHERE id = 37;
UPDATE race SET image_id = 0 WHERE id = 38;
UPDATE race SET image_id = 18 WHERE id = 39;
UPDATE race SET image_id = 0 WHERE id = 40;
